import type { ConceptCard } from '../types/models'

// 돈 개념 사전. 화면에 하드코딩하지 않고 이 파일에서만 관리한다(§4).
// status: 'in_review'인 카드는 body를 비워두고, 검증되지 않은 사실·수치를
// 임의로 채우지 않는다(§5, §19).
export const CONCEPTS: ConceptCard[] = [
  // ══════════════════════════ 생활경제 ══════════════════════════
  {
    id: 'income',
    title: '수입',
    shortDefinition: '일정 기간 동안 벌어들이는 돈이에요.',
    body: '수입은 근로소득, 사업소득, 이자·배당 같은 금융소득 등 일정 기간(주로 한 달)에 들어오는 돈 전체를 말합니다. 가계부에서는 지출·저축의 기준이 되는 출발점입니다.',
    keyPoints: ['정기적으로 들어오는 수입과 비정기적인 수입을 구분해두면 예산을 세우기 쉬워요.', '세금·보험료를 뗀 실수령액을 기준으로 계획하는 것이 일반적이에요.'],
    relatedConceptIds: ['expense', 'cash-flow', 'budget'],
    category: 'daily-finance',
    sourceIds: ['fss-edu'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'expense',
    title: '지출',
    shortDefinition: '일정 기간 동안 쓰는 돈이에요.',
    body: '지출은 생활비, 대출 이자, 보험료 등 일정 기간에 나가는 돈 전체를 말합니다. 지출은 매달 비슷한 금액이 나가는 고정비와, 달마다 금액이 달라지는 변동비로 나눠볼 수 있습니다.',
    keyPoints: ['지출을 항목별로 나눠보면 어디서 줄일 여지가 있는지 파악하기 쉬워요.', '고정비와 변동비를 구분하면 예산을 세울 때 도움이 돼요.'],
    relatedConceptIds: ['income', 'fixed-cost', 'variable-cost'],
    category: 'daily-finance',
    sourceIds: ['fss-edu'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'cash-flow',
    title: '현금흐름',
    shortDefinition: '일정 기간 동안 돈이 들어오고 나가는 흐름이에요.',
    body: '현금흐름은 수입(들어오는 돈)과 지출(나가는 돈)을 함께 놓고 본 흐름입니다. 수입이 지출보다 많으면 현금흐름이 플러스(+)이고, 그 차액이 저축·투자로 남습니다.',
    keyPoints: ['현금흐름이 꾸준히 플러스인지 확인하면 저축 여력을 가늠할 수 있어요.', '큰 지출이 몰리는 달에는 일시적으로 마이너스가 될 수 있어요.'],
    relatedConceptIds: ['income', 'expense', 'budget'],
    category: 'daily-finance',
    sourceIds: ['fss-edu'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'fixed-cost',
    title: '고정비',
    shortDefinition: '매달 거의 같은 금액이 나가는 지출이에요.',
    body: '월세, 보험료, 통신비, 구독료처럼 사용량과 관계없이 매달 비슷한 금액이 빠져나가는 지출입니다. 한 번 줄이면 그 효과가 계속 이어진다는 특징이 있습니다.',
    keyPoints: ['고정비 비중이 너무 높으면 소득이 줄었을 때 대응할 여유가 줄어들어요.', '구독 서비스처럼 잊고 지내는 고정비가 있는지 주기적으로 점검할 수 있어요.'],
    relatedConceptIds: ['variable-cost', 'expense', 'budget'],
    category: 'daily-finance',
    sourceIds: ['fss-edu'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'variable-cost',
    title: '변동비',
    shortDefinition: '달마다 금액이 달라지는 지출이에요.',
    body: '식비, 쇼핑, 여가비처럼 그달의 소비 습관과 상황에 따라 금액이 오르내리는 지출입니다. 고정비보다 상대적으로 조절할 여지가 큰 편입니다.',
    keyPoints: ['변동비는 즉흥적인 소비의 영향을 많이 받아요.', '몇 달치 변동비 평균을 보면 실제 생활비 규모를 가늠하기 쉬워요.'],
    relatedConceptIds: ['fixed-cost', 'expense', 'budget'],
    category: 'daily-finance',
    sourceIds: ['fss-edu'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'budget',
    title: '예산',
    shortDefinition: '일정 기간의 수입과 지출을 미리 짜는 계획이에요.',
    body: '예산은 앞으로의 수입을 어디에 얼마나 쓸지 미리 정해두는 계획입니다. 카테고리별로 한도를 정해두면 실제 지출과 비교하며 소비 습관을 점검할 수 있습니다.',
    keyPoints: ['예산은 한 번 세우고 끝나는 게 아니라 실제 지출과 비교하며 조정하는 과정이에요.', '고정비를 먼저 반영하고 남은 금액으로 변동비 예산을 짜는 방식이 흔히 쓰여요.'],
    relatedConceptIds: ['fixed-cost', 'variable-cost', 'cash-flow'],
    category: 'daily-finance',
    sourceIds: ['fss-edu'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'opportunity-cost',
    title: '기회비용',
    shortDefinition: '한 선택을 하면서 포기하게 되는 다른 선택의 가치예요.',
    body: '돈이나 시간을 한 곳에 쓰면 동시에 다른 곳에는 쓸 수 없습니다. 기회비용은 그 선택 때문에 포기한 대안 중 가장 가치 있었을 것의 가치를 말합니다.',
    keyPoints: ['눈에 보이는 비용(가격표) 말고도 포기한 대안이 있다는 걸 생각해보는 개념이에요.', '저축·투자·소비 중 하나를 고를 때도 기회비용을 따져볼 수 있어요.'],
    relatedConceptIds: ['budget'],
    category: 'daily-finance',
    sourceIds: ['fss-edu'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'emergency-fund',
    title: '비상자금',
    shortDefinition: '갑작스러운 지출에 대비해 투자와 별도로 마련해두는, 언제든 꺼내 쓸 수 있는 돈이에요.',
    body: '비상자금은 실직, 질병, 갑작스러운 수리비처럼 예상하지 못한 지출이 생겼을 때를 대비해 미리 마련해두는 돈입니다. 투자자산과 달리 필요할 때 손실 없이 바로 꺼내 쓸 수 있어야 한다는 점이 특징입니다.\n\n월 생활비가 200만원이라면, 3~6개월치인 600만~1,200만원 정도를 예금이나 CMA처럼 바로 인출 가능한 곳에 따로 모아두는 방식이 흔히 쓰입니다. 정확한 금액은 소득 안정성, 부양가족 유무 등에 따라 사람마다 다릅니다.',
    keyPoints: [
      '생활비 몇 개월치가 바로 인출 가능한 형태로 준비되어 있는지 확인해볼 수 있어요.',
      '비상자금과 투자자금이 같은 계좌에 섞여 있지 않은지 확인해볼 수 있어요.',
    ],
    caution: '비상자금이 없으면 급한 지출이 생겼을 때 투자 중인 자산을 손해를 보더라도 급하게 팔아야 하거나, 높은 금리의 대출에 의존하게 될 수 있어요.',
    relatedConceptIds: ['savings-rate', 'cash-flow'],
    category: 'daily-finance',
    sourceIds: ['fss-edu'],
    reviewedAt: '2026-08-24',
    version: 2,
    status: 'reviewed',
  },
  {
    id: 'savings-rate',
    title: '저축률',
    shortDefinition: '번 돈 중에서 쓰지 않고 저축·투자로 남긴 비율이에요.',
    body: "저축률은 일정 기간의 소득(주로 월 소득) 중에서 저축이나 투자로 남긴 금액이 차지하는 비율입니다. 흔히 '월 저축·투자액 ÷ 월 소득 × 100'으로 계산합니다. 대출 원금 상환도 자산을 늘리는 성격이 있어 함께 넣어 계산하는 경우도 있습니다.\n\n월 소득이 400만원이고 매달 100만원을 저축·투자한다면 저축률은 25%입니다.",
    keyPoints: [
      '저축률은 특정 자산의 수익률보다 스스로 조절하기 쉬운 지표예요.',
      '대출 원금 상환을 포함할지는 스스로 기준을 정해볼 수 있어요.',
    ],
    relatedConceptIds: ['emergency-fund', 'budget'],
    category: 'daily-finance',
    sourceIds: ['fss-edu'],
    reviewedAt: '2026-08-24',
    version: 2,
    status: 'reviewed',
  },

  // ══════════════════════════ 금리·물가·통화 ══════════════════════════
  {
    id: 'money',
    title: '돈(화폐)',
    shortDefinition: '사람들이 서로 믿고 물건·서비스를 사고파는 데 공통으로 쓰는 수단이에요.',
    body: '돈(화폐)은 물건이나 서비스를 사고팔 때 공통으로 쓰이는 교환 수단입니다. 조개껍데기, 금속, 종이, 지금의 전자화된 예금까지 형태는 시대마다 달랐지만, "여러 사람이 그 가치를 믿고 받아준다"는 신뢰가 화폐로 기능하기 위한 핵심 조건이었다고 설명됩니다.',
    keyPoints: ['화폐는 교환의 매개, 가치의 저장, 가치 측정의 기준이라는 여러 역할을 함께 해요.', '화폐로 인정받으려면 많은 사람이 그 가치를 믿고 받아줘야 해요.'],
    relatedConceptIds: ['medium-of-exchange', 'store-of-value', 'price'],
    category: 'money-interest',
    sourceIds: ['bok-economic-history'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'medium-of-exchange',
    title: '교환의 매개',
    shortDefinition: '물건과 물건을 직접 바꾸지 않고, 그 사이에서 거래를 이어주는 역할이에요.',
    body: '교환의 매개는 화폐가 하는 여러 역할 중 하나로, 서로 다른 물건을 가진 사람들이 화폐를 거쳐 원하는 것을 주고받을 수 있게 해주는 기능입니다. 물물교환은 서로 원하는 것이 정확히 맞아떨어져야 거래가 되지만, 화폐가 있으면 이 문제를 피할 수 있다고 설명됩니다.',
    keyPoints: ['물물교환은 "내가 원하는 걸 가진 사람이, 마침 내가 가진 걸 원해야" 거래가 성립돼요.', '화폐는 그 중간 단계 역할을 해서 거래를 훨씬 쉽게 만들어줘요.'],
    relatedConceptIds: ['money', 'store-of-value'],
    category: 'money-interest',
    sourceIds: ['bok-economic-history'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'store-of-value',
    title: '가치의 저장',
    shortDefinition: '화폐가 시간이 지나도 가치를 어느 정도 유지해, 나중에 쓸 수 있게 해주는 기능이에요.',
    body: '가치의 저장은 화폐가 하는 또 다른 역할로, 지금 당장 쓰지 않고 나중에 쓰기 위해 가치를 보관해두는 기능입니다. 상하기 쉬운 물건과 달리, 화폐는(형태에 따라 정도 차이는 있지만) 비교적 오래 가치를 유지할 수 있다는 점이 화폐로 널리 받아들여진 이유 중 하나로 설명됩니다.',
    keyPoints: ['물가가 심하게 오르면(인플레이션) 화폐의 가치 저장 기능이 약해질 수 있어요.'],
    relatedConceptIds: ['money', 'inflation-and-purchasing-power'],
    category: 'money-interest',
    sourceIds: ['bok-economic-history'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'price',
    title: '가격',
    shortDefinition: '어떤 물건이나 서비스를 사고팔 때 매겨지는 화폐 단위의 값이에요.',
    body: '가격은 시장에서 물건이나 서비스가 화폐 단위로 얼마에 거래되는지를 나타냅니다. 수요(사려는 사람)와 공급(팔려는 사람)이 만나는 지점에서 가격이 정해진다고 설명되며, 여러 상품의 가격 변화를 종합한 것이 물가입니다.',
    keyPoints: ['개별 상품의 가격이 모여 물가 지표(소비자물가지수 등)를 이뤄요.'],
    relatedConceptIds: ['money', 'consumer-price-index'],
    category: 'money-interest',
    sourceIds: ['bok-economic-history'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'interest-rate',
    title: '금리',
    shortDefinition: '돈을 빌리거나 맡길 때 적용되는 이자의 비율이에요.',
    body: '금리는 원금 대비 일정 기간 붙는 이자의 비율(%)입니다. 예금·적금처럼 돈을 맡길 때는 받는 이자의 비율이 되고, 대출처럼 돈을 빌릴 때는 내야 하는 이자의 비율이 됩니다.',
    keyPoints: ['같은 금리라도 단리인지 복리인지에 따라 실제로 붙는 이자 금액이 달라져요.', '금리는 중앙은행의 기준금리, 시장 상황 등 여러 요인에 따라 오르내려요.'],
    relatedConceptIds: ['base-rate', 'simple-vs-compound-interest', 'interest'],
    category: 'money-interest',
    sourceIds: ['bok-edu'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'base-rate',
    title: '기준금리',
    shortDefinition: '중앙은행이 물가와 경기를 조절하기 위해 정하는 정책금리예요.',
    body: '기준금리는 한국은행 같은 중앙은행이 금융통화위원회 등을 통해 결정하는 정책금리입니다. 은행 간 자금 거래 금리의 기준이 되어, 예금·대출 금리를 비롯한 시장금리 전반에 영향을 줍니다.',
    keyPoints: ['기준금리를 올리면 대체로 시중 대출·예금 금리도 따라 오르는 경향이 있어요.', '물가가 많이 오를 때는 금리를 올리고, 경기가 부진할 때는 낮추는 방향으로 쓰이는 경우가 많아요.'],
    relatedConceptIds: ['central-bank', 'interest-rate', 'money-supply'],
    category: 'money-interest',
    sourceIds: ['bok-edu', 'bok-ecos'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'simple-vs-compound-interest',
    title: '단리와 복리',
    shortDefinition: '단리는 원금에만, 복리는 원금과 이미 붙은 이자에도 다시 이자가 붙는 방식이에요.',
    body: '단리는 처음 맡긴 원금에 대해서만 매번 같은 비율로 이자가 붙는 방식입니다. 복리는 한 번 붙은 이자가 원금에 합쳐져서, 다음번에는 그 합쳐진 금액을 기준으로 다시 이자가 붙는 방식입니다.\n\n100만원을 연 5%로 3년간 맡긴다면, 단리는 매년 5만원씩 총 15만원의 이자가 붙어 115만원이 됩니다. 복리(연 1회 복리 가정)는 1년 차 105만원, 2년 차 약 110만 2,500원, 3년 차 약 115만 7,625원으로 단리보다 조금 더 많아집니다.',
    keyPoints: [
      '기간이 길어질수록 복리와 단리의 차이는 점점 커져요.',
      '이자·배당을 다시 투자(재투자)해야 복리 효과가 이어져요.',
    ],
    caution: '적금·예금의 이자 지급 방식이나 투자 상품의 재투자 여부에 따라 실제로 붙는 이자·수익 방식이 달라질 수 있어, 상품 설명에서 단리인지 복리인지 확인하는 습관이 도움이 돼요.',
    relatedConceptIds: ['interest-rate', 'nominal-vs-real-rate'],
    category: 'money-interest',
    sourceIds: ['bok-edu'],
    reviewedAt: '2026-08-24',
    version: 2,
    status: 'reviewed',
  },
  {
    id: 'nominal-vs-real-rate',
    title: '명목금리와 실질금리',
    shortDefinition: '명목금리는 통장에 찍히는 숫자 그대로의 금리, 실질금리는 물가상승률을 뺀 진짜 구매력 기준 금리예요.',
    body: "명목금리는 은행이나 상품 설명서에 표시되는 그대로의 금리입니다. 실질금리는 명목금리에서 물가상승률을 뺀 값으로, 실제로 돈의 구매력이 얼마나 늘었는지를 보여줍니다. 대략 '실질금리 ≈ 명목금리 − 물가상승률'로 어림잡아 볼 수 있습니다.\n\n예금 명목금리가 연 3%인데 그해 물가상승률이 3.5%였다면, 실질금리는 약 −0.5%가 됩니다.",
    keyPoints: [
      '명목금리만 보고 이자를 받았다고 생각하기 쉽지만, 물가상승률이 더 높으면 실질 구매력은 줄어들 수 있어요.',
      '예금·채권처럼 금리가 정해진 자산을 평가할 때 실질금리 개념이 도움이 돼요.',
    ],
    relatedConceptIds: ['inflation-and-purchasing-power', 'simple-vs-compound-interest'],
    category: 'money-interest',
    sourceIds: ['bok-edu'],
    reviewedAt: '2026-08-24',
    version: 2,
    status: 'reviewed',
  },
  {
    id: 'inflation-and-purchasing-power',
    title: '물가와 구매력',
    shortDefinition: '물가가 오르면 같은 돈으로 살 수 있는 양이 줄어드는데, 이걸 구매력이 줄었다고 표현해요.',
    body: '구매력은 일정 금액의 돈으로 실제 살 수 있는 재화·서비스의 양을 뜻합니다. 물가가 오르면(인플레이션) 같은 금액이라도 살 수 있는 양이 줄어들어 구매력이 감소합니다.\n\n물가상승률이 연 3%라면, 지금 100만원으로 살 수 있는 물건을 10년 뒤에 사려면 대략 134만원 정도가 필요해집니다.',
    keyPoints: [
      '현금이나 초저금리 자산만 오래 들고 있으면 명목 금액은 그대로여도 구매력은 계속 줄어들 수 있어요.',
      '목돈을 오래 보관할 계획이라면 물가상승률을 함께 고려하는 것이 도움이 돼요.',
    ],
    relatedConceptIds: ['nominal-vs-real-rate', 'inflation', 'consumer-price-index'],
    category: 'money-interest',
    sourceIds: ['bok-edu'],
    reviewedAt: '2026-08-24',
    version: 2,
    status: 'reviewed',
  },
  {
    id: 'inflation',
    title: '인플레이션',
    shortDefinition: '물가가 전반적으로, 지속적으로 오르는 현상이에요.',
    body: '인플레이션은 특정 상품 하나가 아니라 경제 전반의 물가 수준이 지속적으로 오르는 현상입니다. 수요가 공급보다 많아지거나, 원자재·인건비 같은 생산비용이 오르거나, 시중에 통화량이 많이 풀릴 때 등 여러 원인으로 나타날 수 있습니다.',
    keyPoints: ['적당한 인플레이션은 경기 활력의 신호로 여겨지기도 하지만, 지나치게 빠르면 생활에 부담을 줘요.', '반대로 물가가 지속적으로 내려가는 현상은 디플레이션이라고 해요.'],
    relatedConceptIds: ['inflation-and-purchasing-power', 'deflation', 'consumer-price-index'],
    category: 'money-interest',
    sourceIds: ['bok-edu'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'deflation',
    title: '디플레이션',
    shortDefinition: '물가가 전반적으로, 지속적으로 내려가는 현상이에요.',
    body: '디플레이션은 경제 전반의 물가 수준이 지속적으로 하락하는 현상입니다. 물건값이 계속 내려갈 것으로 예상되면 소비와 투자를 미루는 경향이 생겨, 경기 부진이 길어지는 악순환으로 이어질 수 있다고 설명되곤 합니다.',
    keyPoints: ['물가가 떨어지는 게 항상 좋은 것만은 아니라고 여겨지는 이유가 여기에 있어요.', '디플레이션은 인플레이션보다 드물게 나타나는 현상으로 다뤄져요.'],
    relatedConceptIds: ['inflation', 'stagflation'],
    category: 'money-interest',
    sourceIds: ['bok-edu'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'stagflation',
    title: '스태그플레이션',
    shortDefinition: '경기 부진과 물가 상승이 동시에 나타나는 상황이에요.',
    body: '스태그플레이션은 경기 침체(stagnation)와 인플레이션(inflation)을 합친 말로, 경제 성장은 부진한데 물가는 오히려 오르는 상황을 가리킵니다. 보통 물가와 경기는 반대로 움직인다고 여겨지는데, 이 둘이 동시에 나쁜 방향으로 갈 때 정책 대응이 더 어려워진다고 설명됩니다.',
    keyPoints: ['금리를 올려 물가를 잡으면 경기가 더 나빠질 수 있고, 경기를 살리려 하면 물가가 더 오를 수 있어 대응이 까다로워요.', '1970년대 오일쇼크 시기가 대표적인 사례로 꼽혀요.'],
    relatedConceptIds: ['inflation', 'oil-shock', 'base-rate'],
    category: 'money-interest',
    sourceIds: ['bok-edu'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'consumer-price-index',
    title: '소비자물가지수',
    shortDefinition: '가계가 자주 사는 물건과 서비스 가격을 모아 물가 수준을 나타낸 지표예요.',
    body: '소비자물가지수(CPI)는 가계가 일상적으로 구입하는 상품과 서비스의 가격 변동을 종합해 만든 지표입니다. 통계청이 매달 발표하며, 이 지표의 변화율이 흔히 말하는 "물가상승률"의 근거로 쓰입니다.',
    keyPoints: ['모든 품목이 똑같이 오르내리지 않아서, 체감 물가와 지수 물가가 다르게 느껴질 수 있어요.', '전월비·전년동월비로 비교해서 물가 흐름을 살펴보는 경우가 많아요.'],
    relatedConceptIds: ['inflation', 'inflation-and-purchasing-power'],
    category: 'money-interest',
    sourceIds: ['kostat-info'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'money-supply',
    title: '통화량',
    shortDefinition: '경제 안에 돌고 있는 돈의 총량이에요.',
    body: '통화량은 현금과 예금 등 경제 전체에 유통되고 있는 돈의 규모를 나타내는 지표입니다. 중앙은행의 정책이나 은행의 대출 활동에 따라 늘거나 줄어들 수 있습니다.',
    keyPoints: ['통화량이 지나치게 빠르게 늘면 물가 상승 압력으로 이어질 수 있다고 설명돼요.', '중앙은행은 기준금리나 여러 정책 수단으로 통화량에 영향을 주려고 해요.'],
    relatedConceptIds: ['central-bank', 'base-rate', 'inflation'],
    category: 'money-interest',
    sourceIds: ['bok-edu', 'bok-ecos'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'exchange-rate-and-foreign-assets',
    title: '환율과 해외자산',
    shortDefinition: '해외자산은 그 자산의 가격뿐 아니라, 원화와 외화 사이의 환율 변화에도 함께 영향을 받아요.',
    body: '해외 주식이나 외화 예금처럼 원화가 아닌 통화로 표시된 자산은, 그 자산 자체의 가격 변화와 더불어 원/외화 환율 변화가 원화 환산 가치에 함께 반영됩니다.\n\n미국 주식이 달러 기준으로 그대로였어도, 원/달러 환율이 오르면(원화 약세) 원화로 환산한 가치는 늘어날 수 있고, 반대로 환율이 내리면(원화 강세) 줄어들 수 있습니다.',
    keyPoints: ['해외자산에 투자할 때는 자산 가격 변화와 환율 변화가 같은 방향일 수도, 반대 방향일 수도 있어요.', '보유한 해외자산의 최근 수익률이 자산 가격 때문인지 환율 때문인지 나눠볼 수 있어요.'],
    relatedConceptIds: ['diversification'],
    category: 'money-interest',
    sourceIds: ['bok-edu'],
    reviewedAt: '2026-08-24',
    version: 2,
    status: 'reviewed',
  },

  // ══════════════════════════ 부채·신용 ══════════════════════════
  {
    id: 'principal',
    title: '원금',
    shortDefinition: '이자가 붙기 전, 처음 맡기거나 빌린 돈이에요.',
    body: '원금은 예금·적금이라면 처음 맡긴 돈, 대출이라면 처음 빌린 돈을 말합니다. 이자는 이 원금을 기준으로 계산됩니다.',
    keyPoints: ['대출을 갚을 때 원금과 이자를 각각 얼마씩 갚고 있는지 구분해보면 도움이 돼요.'],
    relatedConceptIds: ['interest', 'loan'],
    category: 'debt-credit',
    sourceIds: ['fss-edu'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'interest',
    title: '이자',
    shortDefinition: '돈을 빌려주거나 맡긴 대가로 주고받는 돈이에요.',
    body: '이자는 원금을 빌려주거나 맡긴 사람이 그 대가로 받는 돈입니다. 예금이라면 은행이 예금자에게 이자를 주고, 대출이라면 대출자가 은행에 이자를 냅니다. 금리(비율)와 기간에 따라 이자 금액이 정해집니다.',
    keyPoints: ['같은 원금이어도 금리가 높을수록, 기간이 길수록 이자가 커져요.', '단리·복리 방식에 따라 실제로 붙는 이자 금액이 달라져요.'],
    relatedConceptIds: ['principal', 'interest-rate', 'simple-vs-compound-interest'],
    category: 'debt-credit',
    sourceIds: ['fss-edu'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'loan',
    title: '대출',
    shortDefinition: '금융회사 등에서 돈을 빌리고, 나중에 이자와 함께 갚기로 약속하는 거래예요.',
    body: '대출은 은행 같은 금융회사에서 돈을 빌리고, 정해진 기간 동안 이자를 더해 갚기로 약속하는 거래입니다. 금리가 고정인지 변동인지, 상환 방식이 무엇인지에 따라 매달 갚는 금액과 총이자가 달라집니다.',
    keyPoints: ['대출은 필요한 자금을 미리 당겨쓰는 대신, 그만큼 이자 비용이 발생해요.', '상환 능력을 벗어난 대출은 생활에 부담을 줄 수 있어요.'],
    relatedConceptIds: ['loan-rate-and-repayment', 'interest', 'credit'],
    category: 'debt-credit',
    sourceIds: ['fss-edu'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'loan-rate-and-repayment',
    title: '대출금리와 상환방식',
    shortDefinition: '대출은 고정·변동금리 여부와, 원리금균등·원금균등 같은 상환방식에 따라 매달 갚는 금액과 총이자가 달라져요.',
    body: '대출금리는 고정금리(계약 기간 내내 동일)와 변동금리(일정 주기로 시장금리에 따라 바뀜)로 나뉩니다. 상환방식은 매달 원금과 이자를 같은 금액으로 나눠 갚는 원리금균등상환, 원금은 매달 동일하고 이자만 줄어드는 원금균등상환 등이 있으며, 방식에 따라 초기 상환 부담과 총이자가 달라집니다.\n\n같은 금액을 빌려도 원금균등상환은 초반에 갚는 금액이 더 크고 시간이 지날수록 줄어드는 반면, 원리금균등상환은 매달 갚는 금액이 일정합니다.',
    keyPoints: [
      '내 대출이 고정금리인지 변동금리인지 확인해볼 수 있어요.',
      '변동금리라면 다음 금리 조정일이 언제인지 확인해볼 수 있어요.',
    ],
    caution: '기준금리가 바뀌면 변동금리 대출의 상환 부담이 달라질 수 있어요.',
    relatedConceptIds: ['fixed-rate', 'floating-rate', 'nominal-vs-real-rate'],
    category: 'debt-credit',
    sourceIds: ['fss-edu'],
    reviewedAt: '2026-08-24',
    version: 2,
    status: 'reviewed',
  },
  {
    id: 'fixed-rate',
    title: '고정금리',
    shortDefinition: '계약 기간 내내 똑같이 유지되는 금리예요.',
    body: '고정금리는 대출이나 예금 계약을 맺을 때 정한 금리가 만기까지 바뀌지 않는 방식입니다. 시장금리가 올라도 내가 내는(받는) 금리는 그대로라는 점이 특징입니다.',
    keyPoints: ['시장금리가 오를 것으로 예상될 때 고정금리 대출이 유리할 수 있다고 이야기돼요.', '반대로 시장금리가 내리면 고정금리 대출이 상대적으로 불리해질 수 있어요.'],
    relatedConceptIds: ['floating-rate', 'loan-rate-and-repayment'],
    category: 'debt-credit',
    sourceIds: ['fss-edu'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'floating-rate',
    title: '변동금리',
    shortDefinition: '일정 주기로 시장금리에 따라 바뀌는 금리예요.',
    body: '변동금리는 일정 주기(3개월, 6개월 등)마다 기준이 되는 시장금리에 맞춰 다시 정해지는 금리 방식입니다. 시장금리가 오르면 다음 조정일부터 내가 내는(받는) 금리도 함께 오릅니다.',
    keyPoints: ['보통 고정금리보다 시작할 때 금리가 낮게 제시되는 경우가 많다고 알려져 있어요.', '금리가 오르는 시기에는 상환 부담이 커질 수 있어요.'],
    relatedConceptIds: ['fixed-rate', 'loan-rate-and-repayment', 'base-rate'],
    category: 'debt-credit',
    sourceIds: ['fss-edu'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'credit',
    title: '신용',
    shortDefinition: '약속한 돈을 갚을 수 있다고 인정받는 능력이나 그 평가예요.',
    body: '신용은 돈을 빌린 사람이 약속대로 갚을 수 있는지에 대한 평가입니다. 소득, 기존 대출·연체 이력 등을 바탕으로 신용점수·등급이 매겨지고, 이는 대출 가능 여부와 금리에 영향을 줍니다.',
    keyPoints: ['연체 없이 꾸준히 갚아온 이력이 신용에 긍정적으로 반영되는 경우가 많아요.', '신용이 높을수록 대체로 더 낮은 금리로 대출받을 수 있는 경향이 있어요.'],
    relatedConceptIds: ['delinquency', 'loan', 'collateral'],
    category: 'debt-credit',
    sourceIds: ['fss-edu'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'collateral',
    title: '담보',
    shortDefinition: '대출을 못 갚을 경우에 대비해 미리 제공하는 재산이에요.',
    body: '담보는 부동산이나 예금처럼, 대출을 갚지 못했을 때 금융회사가 대신 처분해 돈을 회수할 수 있도록 제공하는 재산입니다. 담보가 있는 대출(담보대출)은 보통 담보가 없는 대출(신용대출)보다 금리가 낮게 적용되는 경향이 있습니다.',
    keyPoints: ['담보를 제공하면 대출자가 상환하지 못했을 때 그 재산을 잃을 수 있어요.', '담보 가치가 대출금보다 크게 떨어지면 추가 담보를 요구받을 수 있어요.'],
    relatedConceptIds: ['credit', 'mortgage'],
    category: 'debt-credit',
    sourceIds: ['fss-edu'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'delinquency',
    title: '연체',
    shortDefinition: '정해진 날짜까지 갚기로 한 돈을 갚지 못한 상태예요.',
    body: '연체는 대출 원리금이나 카드값처럼 정해진 기한까지 갚아야 할 돈을 갚지 못한 상태를 말합니다. 연체가 길어지면 연체이자가 추가로 붙고, 신용점수에도 부정적인 영향을 줄 수 있습니다.',
    keyPoints: ['짧은 연체라도 신용 정보에 기록이 남을 수 있어요.', '연체가 예상되면 미리 금융회사와 상담해 대응 방법을 알아볼 수 있어요.'],
    relatedConceptIds: ['credit', 'loan'],
    category: 'debt-credit',
    sourceIds: ['fss-edu'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'mortgage',
    title: '주택담보대출(모기지)',
    shortDefinition: '집을 담보로 잡고 받는 대출이에요.',
    body: '주택담보대출(모기지)은 구입하려는 집이나 이미 가진 부동산을 담보로 제공하고 받는 대출입니다. 담보가 있어 신용대출보다 대체로 큰 금액을, 상대적으로 낮은 금리로 빌릴 수 있는 편입니다.',
    keyPoints: ['집값보다 대출금이 커지면(집값 하락 시) 담보 가치가 대출금에 못 미치는 상황이 생길 수 있어요.', '2008년 세계금융위기는 미국의 부실한 주택담보대출 확산에서 촉발됐다고 설명돼요.'],
    relatedConceptIds: ['collateral', 'loan', 'securitization'],
    category: 'debt-credit',
    sourceIds: ['fss-edu'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'credit-risk',
    title: '신용위험',
    shortDefinition: '돈을 빌려준 상대가 약속대로 갚지 못할 위험이에요.',
    body: '신용위험은 대출이나 채권 투자에서, 돈을 빌린 쪽(차주)이 원리금을 제때 갚지 못할 가능성을 말합니다. 신용위험이 높다고 평가될수록 대출·채권 금리가 높게 매겨지는 경향이 있습니다.',
    keyPoints: ['신용위험이 특정 대출 하나가 아니라 여러 대출·기관에 동시에 번지면 금융위기로 이어질 수 있다고 설명돼요.'],
    relatedConceptIds: ['credit', 'mortgage', 'financial-crisis'],
    category: 'debt-credit',
    sourceIds: ['fss-edu'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'leverage',
    title: '레버리지',
    shortDefinition: '빌린 돈을 더해 투자 규모를 키우는 방법이에요.',
    body: '레버리지(지렛대 효과)는 대출 등으로 빌린 돈을 자기자본에 더해 투자 규모를 키우는 것을 말합니다. 수익이 날 때는 자기자본만 투자했을 때보다 수익률이 커지지만, 손실이 날 때도 손실률이 그만큼 커집니다.',
    keyPoints: ['레버리지는 수익뿐 아니라 손실도 함께 키운다는 점을 이해해두는 게 중요해요.', '빌린 돈에는 이자 비용이 따로 든다는 점도 함께 고려해야 해요.'],
    relatedConceptIds: ['loan', 'volatility', 'risk'],
    category: 'debt-credit',
    sourceIds: ['fss-edu'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },

  // ══════════════════════════ 투자 ══════════════════════════
  {
    id: 'investing',
    title: '투자',
    shortDefinition: '수익을 기대하며 자산을 사고, 그에 따른 손실 가능성도 함께 안는 활동이에요.',
    body: '투자는 주식, 채권, 부동산 등 자산을 사서 가격 상승이나 배당·이자 같은 수익을 기대하는 활동입니다. 예금과 달리 원금이 보장되지 않고, 기대한 수익이 나지 않거나 손실이 날 수도 있습니다.',
    keyPoints: ['투자는 기대수익과 함께 손실 가능성을 반드시 동반해요.', '무엇에, 얼마나, 얼마나 오래 투자할지는 개인의 목적과 상황에 따라 달라져요.'],
    relatedConceptIds: ['risk', 'expected-return', 'diversification'],
    category: 'investing',
    sourceIds: ['fss-edu'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'risk',
    title: '위험',
    shortDefinition: '투자한 결과가 기대와 다르게(특히 나쁘게) 나타날 가능성이에요.',
    body: '투자에서 위험은 단순히 "위험하다"는 느낌이 아니라, 실제 결과가 기대했던 수익과 다르게 나타날 가능성 전반을 말합니다. 가격이 크게 오르내리는 변동성도 위험의 한 형태로 다뤄집니다.',
    keyPoints: ['위험이 크다고 항상 나쁜 것은 아니지만, 감당할 수 있는 수준인지 스스로 점검이 필요해요.', '위험을 아예 없앨 수는 없어도 분산 등으로 줄일 수는 있어요.'],
    relatedConceptIds: ['volatility', 'investing', 'diversification'],
    category: 'investing',
    sourceIds: ['fss-edu'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'speculation',
    title: '투기',
    shortDefinition: '가격 변동만 노리고 짧은 기간에 큰 차익을 노리는 거래를 흔히 이렇게 불러요.',
    body: '투기는 자산의 실제 가치보다는 가격이 계속 오를 것이라는 기대에 기대어 짧은 기간에 차익을 노리는 거래를 가리킬 때 쓰이는 말입니다. 투자와 투기의 경계가 항상 명확한 것은 아니며, 기간·목적·분석 방식 등으로 구분하려는 시도가 있습니다.',
    keyPoints: ['투기적 거래는 가격 변동성이 크고, 예상이 빗나갔을 때 손실도 클 수 있어요.', '역사적으로 자산 거품이 형성될 때 투기적 수요가 함께 늘어난 경우가 많았다고 설명돼요.'],
    relatedConceptIds: ['asset-bubble', 'volatility', 'risk'],
    category: 'investing',
    sourceIds: ['fss-edu'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'expected-return',
    title: '기대수익률',
    shortDefinition: '앞으로 이 정도 수익이 날 것이라고 가정한 값으로, 실제 결과를 보장하지 않아요.',
    body: '기대수익률은 과거 데이터나 가정을 바탕으로 "평균적으로 이 정도 수익이 나지 않을까" 추정한 값입니다. 실제 수익률은 이보다 높을 수도, 낮을 수도, 마이너스가 될 수도 있습니다.',
    keyPoints: ['기대수익률은 과거 자료를 바탕으로 한 가정일 뿐, 미래 수익을 보장하지 않아요.', '기대수익이 높은 자산은 대체로 위험(변동성)도 함께 높은 경향이 있다고 설명돼요.'],
    relatedConceptIds: ['risk', 'volatility', 'return-and-breakeven'],
    category: 'investing',
    sourceIds: ['fss-edu'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'return-and-breakeven',
    title: '수익률과 원금 회복률',
    shortDefinition: '손실이 나면, 원금을 회복하는 데 필요한 수익률은 손실률보다 항상 더 커요.',
    body: '수익률은 투자 원금 대비 늘어나거나 줄어든 비율입니다. 원금 회복률은 손실이 난 뒤 원래 금액으로 되돌아오기 위해 필요한 수익률로, 손실률과 같은 숫자가 아닙니다.\n\n100만원이 20% 하락하면 80만원이 됩니다. 80만원이 다시 100만원이 되려면 20%가 아니라 25% 상승해야 합니다. 50% 하락했다면 원금 회복에는 100% 상승이 필요합니다.',
    keyPoints: ['하락폭이 커질수록 원금을 회복하는 데 필요한 상승폭은 훨씬 더 커져요.', '이 비대칭성 때문에 큰 손실을 피하는 것이 큰 수익을 노리는 것만큼 중요하다고 이야기돼요.'],
    relatedConceptIds: ['investment-horizon-and-volatility', 'expected-return'],
    category: 'investing',
    sourceIds: ['fss-edu'],
    reviewedAt: '2026-08-24',
    version: 2,
    status: 'reviewed',
  },
  {
    id: 'volatility',
    title: '변동성',
    shortDefinition: '자산 가격이 오르내리는 폭을 뜻해요.',
    body: '변동성은 일정 기간 동안 자산 가격이 얼마나 크게 오르내렸는지를 나타냅니다. 변동성이 크다는 건 가격이 짧은 기간에도 크게 움직일 수 있다는 뜻으로, 위험을 가늠하는 대표적인 척도로 쓰입니다.',
    keyPoints: ['변동성이 큰 자산은 단기간에 크게 오를 수도, 크게 내릴 수도 있어요.', '투자 기간이 길면 단기 변동성을 견딜 여유가 상대적으로 더 생겨요.'],
    relatedConceptIds: ['investment-horizon-and-volatility', 'risk'],
    category: 'investing',
    sourceIds: ['fss-edu'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'diversification',
    title: '분산투자',
    shortDefinition: '여러 자산에 나눠 담아서, 하나가 크게 흔들려도 전체 충격을 줄이는 방법이에요.',
    body: '분산투자는 자금을 하나의 자산이 아니라 여러 자산(국가, 업종, 자산군 등)에 나누어 투자하는 방법입니다. 서로 다르게 움직이는 자산을 섞으면 전체 자산의 흔들림 폭을 줄이는 효과를 기대할 수 있습니다.\n\n국내 주식 한 종목에만 전부 투자하는 대신, 국내주식·해외주식·채권·현금성 자산에 나누어 담는 경우가 분산투자의 예입니다.',
    keyPoints: ['현재 투자자산이 특정 종목·국가·업종에 몰려 있지 않은지 확인해볼 수 있어요.', 'ETF 하나에 여러 기업이 담겨 있는 것도 일종의 분산 효과가 있어요.'],
    caution: '분산투자를 한다고 손실 자체가 사라지는 것은 아니며, 실제 효과는 자산 간 상관관계 등 여러 조건에 따라 달라져요.',
    relatedConceptIds: ['investment-horizon-and-volatility', 'stocks-bonds-etfs', 'asset-allocation'],
    category: 'investing',
    sourceIds: ['fss-edu'],
    reviewedAt: '2026-08-24',
    version: 2,
    status: 'reviewed',
  },
  {
    id: 'asset-allocation',
    title: '자산배분',
    shortDefinition: '현금·예금·주식·채권 같은 자산군에 얼마씩 나눌지 정하는 것이에요.',
    body: '자산배분은 투자 가능한 돈을 현금성 자산, 채권, 주식 등 서로 다른 성격의 자산군에 어떤 비율로 나눌지 정하는 것입니다. 개별 종목을 고르기 전에, 큰 틀에서 위험과 기대수익의 균형을 잡는 단계로 다뤄집니다.',
    keyPoints: ['같은 종목을 분산해 담는 것과, 자산군 자체를 나누는 자산배분은 서로 다른 층위의 결정이에요.', '나이, 목표 시점, 감당할 수 있는 위험 수준에 따라 적절한 배분이 달라질 수 있어요.'],
    relatedConceptIds: ['diversification', 'risk'],
    category: 'investing',
    sourceIds: ['fss-edu'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'investment-horizon-and-volatility',
    title: '투자기간과 변동성',
    shortDefinition: '투자 기간이 길수록, 짧은 기간의 오르내림(변동성)이 전체 결과에 미치는 영향을 줄일 여유가 생겨요.',
    body: '변동성은 자산 가격이 오르내리는 폭을 뜻합니다. 투자기간은 그 자산을 얼마나 오래 보유할 계획인지를 뜻합니다. 투자기간이 길면 단기적인 가격 변동을 견디고 지나갈 여유가 상대적으로 더 생깁니다.\n\n1~2년 안에 써야 할 자금을 변동성이 큰 자산에 투자했다면, 필요한 시점에 마침 가격이 낮아 손해를 보고 팔아야 할 수 있습니다.',
    keyPoints: [
      '이 돈을 언제쯤 쓸 계획인지 먼저 생각해볼 수 있어요.',
      '그 시점까지 가격이 떨어져도 버틸 수 있는 자산인지 점검해볼 수 있어요.',
    ],
    relatedConceptIds: ['diversification', 'return-and-breakeven', 'volatility'],
    category: 'investing',
    sourceIds: ['fss-edu'],
    reviewedAt: '2026-08-24',
    version: 2,
    status: 'reviewed',
  },
  {
    id: 'liquidity',
    title: '유동성',
    shortDefinition: '자산을 필요할 때 얼마나 빠르고 손해 없이 현금으로 바꿀 수 있는지를 뜻해요.',
    body: '유동성은 자산을 현금으로 바꾸는 데 걸리는 시간과, 그 과정에서 가치 손실이 얼마나 있는지를 함께 나타내는 개념입니다. 예금은 유동성이 높은 편이고, 부동산처럼 사고파는 데 시간이 걸리는 자산은 유동성이 낮은 편입니다.',
    keyPoints: ['급하게 현금이 필요할 수 있는 돈은 유동성이 높은 자산에 두는 것이 일반적이에요.', '유동성이 낮은 자산은 급하게 팔면 제값을 받지 못할 수 있어요.'],
    relatedConceptIds: ['emergency-fund', 'risk'],
    category: 'investing',
    sourceIds: ['fss-edu'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },

  // ══════════════════════════ 금융상품 ══════════════════════════
  {
    id: 'bank',
    title: '은행',
    shortDefinition: '사람들의 돈을 맡아 보관·운용하고, 필요한 사람에게 빌려주는 금융회사예요.',
    body: '은행은 예금자에게서 돈을 맡아(예금) 그중 일부를 다른 사람이나 기업에 빌려주고(대출), 그 과정에서 발생하는 금리 차이 등으로 수익을 얻는 금융회사입니다. 결제·송금 같은 지급 기능도 함께 담당합니다.',
    keyPoints: ['은행에 맡긴 돈은 예금자보호제도의 적용을 받을 수 있어요(한도 안에서).', '은행은 자금을 중개해 돈이 필요한 곳으로 흘러가게 하는 역할을 해요.'],
    relatedConceptIds: ['deposit', 'loan', 'central-bank'],
    category: 'financial-products',
    sourceIds: ['fss-edu'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'deposit',
    title: '예금',
    shortDefinition: '은행 등에 돈을 맡기고 정해진 이자를 받는 금융상품이에요.',
    body: '예금은 은행 같은 금융회사에 돈을 맡기고 정해진 금리에 따라 이자를 받는 상품입니다. 자유롭게 넣고 뺄 수 있는 요구불예금과, 일정 기간 동안 맡기기로 약속하는 정기예금 등으로 나뉩니다.',
    keyPoints: ['일정 한도까지는 예금자보호제도로 보호받을 수 있어요.', '정기예금은 만기 전에 찾으면 약정한 이자보다 적게 받을 수 있어요.'],
    relatedConceptIds: ['bank', 'deposit-protection', 'savings-installment'],
    category: 'financial-products',
    sourceIds: ['fss-edu'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'savings-installment',
    title: '적금',
    shortDefinition: '매달 일정 금액을 나눠 넣고, 만기에 원금과 이자를 함께 받는 상품이에요.',
    body: '적금은 목돈을 한 번에 맡기는 예금과 달리, 정해진 기간 동안 매달 일정 금액을 나눠 넣고 만기에 원금과 이자를 함께 받는 상품입니다. 매달 넣는 돈마다 이자가 붙는 기간이 다르다는 점이 정기예금과의 큰 차이입니다.',
    keyPoints: ['광고에 나온 금리가 전체 납입액에 그대로 적용되는 게 아니라, 매달 낸 돈마다 다르게 계산돼요.', '중도해지하면 약정 금리보다 낮은 이자를 받을 수 있어요.'],
    relatedConceptIds: ['deposit', 'simple-vs-compound-interest'],
    category: 'financial-products',
    sourceIds: ['fss-edu'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'deposit-protection',
    title: '예금자보호',
    shortDefinition: '금융회사가 문제가 생겨도, 한 금융회사당 원금과 이자를 합쳐 1억원까지는 보호돼요.',
    body: '예금자보호제도는 금융회사가 예금 등을 지급할 수 없게 되는 경우에도, 예금보험공사가 일정 한도까지 대신 지급해 예금자를 보호하는 제도입니다. 2025년 9월 1일부터 보호 한도가 기존 5천만원에서 1억원(원금과 이자 합산)으로 상향되어 시행 중입니다.\n\n한 은행에 예금 원금과 이자를 합쳐 1억 2천만원을 맡겼다면, 이 중 1억원까지는 보호되고 나머지 2천만원은 보호 대상이 아닐 수 있습니다.',
    keyPoints: [
      '한 금융회사에 맡긴 예금(원금+이자) 합계가 1억원을 넘는지 확인해볼 수 있어요.',
      '가입한 상품이 예금자보호 대상 상품인지 확인해볼 수 있어요(모든 금융상품이 보호 대상은 아니에요).',
    ],
    relatedConceptIds: ['deposit', 'bank'],
    category: 'financial-products',
    sourceIds: ['kdic-info'],
    reviewedAt: '2026-08-24',
    effectiveDate: '2025-09-01',
    version: 2,
    status: 'reviewed',
  },
  {
    id: 'fund',
    title: '펀드',
    shortDefinition: '여러 투자자의 돈을 모아 전문 운용사가 대신 굴리는 상품이에요.',
    body: '펀드는 여러 사람의 돈을 모아 자산운용사 같은 전문가가 주식·채권 등에 대신 투자하고, 그 성과를 나눠 갖는 상품입니다. 직접 종목을 고르지 않아도 분산투자 효과를 얻을 수 있다는 점이 특징입니다.',
    keyPoints: ['펀드는 운용 성과에 따라 원금 손실이 날 수 있어요.', '운용을 맡기는 대가로 운용보수 등 비용이 들어요.'],
    relatedConceptIds: ['diversification', 'stocks-bonds-etfs'],
    category: 'financial-products',
    sourceIds: ['fss-edu'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'stocks-bonds-etfs',
    title: '주식·채권·ETF의 차이',
    shortDefinition: '주식은 회사 지분, 채권은 빌려준 돈에 대한 증서, ETF는 여러 자산을 묶어 거래소에서 사고파는 상품이에요.',
    body: '주식은 회사의 지분 일부를 소유하는 증권으로, 회사 실적과 시장 평가에 따라 가격이 변합니다. 채권은 정부나 기업에 돈을 빌려주고 받는 증서로, 정해진 이자와 만기 상환을 약속받는 대신 발행자의 상환 능력에 따라 위험이 달라집니다. ETF(상장지수펀드)는 여러 주식·채권 등을 묶어 하나의 상품처럼 거래소에서 매매할 수 있게 만든 것입니다.',
    keyPoints: ['세 가지는 위험과 수익의 성격이 서로 달라요.', '내가 가진 상품이 주식·채권·ETF 중 무엇인지, 무엇을 담고 있는지 확인해볼 수 있어요.'],
    relatedConceptIds: ['diversification', 'dividend', 'fund'],
    category: 'financial-products',
    sourceIds: ['fss-edu'],
    reviewedAt: '2026-08-24',
    version: 2,
    status: 'reviewed',
  },
  {
    id: 'dividend',
    title: '배당',
    shortDefinition: '회사가 벌어들인 이익 일부를 주주에게 나눠주는 돈이에요.',
    body: '배당은 회사가 영업활동으로 얻은 이익 중 일부를 주식을 가진 주주에게 나눠주는 것입니다. 모든 회사가 배당을 주는 것은 아니며, 배당 여부와 금액은 회사의 실적과 정책에 따라 달라질 수 있습니다.',
    keyPoints: ['배당은 주가 상승과는 별개의 수익원으로 다뤄져요.', '배당을 많이 준다고 항상 좋은 회사인 것은 아니고, 회사의 성장 단계에 따라 배당 정책이 달라요.'],
    relatedConceptIds: ['stocks-bonds-etfs'],
    category: 'financial-products',
    sourceIds: ['fss-edu'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'securitization',
    title: '증권화',
    shortDefinition: '대출 채권 같은 자산을 묶어서 사고팔 수 있는 증권으로 만드는 것이에요.',
    body: '증권화는 주택담보대출처럼 개별적으로는 사고팔기 어려운 자산(채권)을 여러 개 묶어, 투자자들이 사고팔 수 있는 증권 형태로 만드는 것을 말합니다. 대출을 해준 금융회사는 이 증권을 팔아 자금을 회수하고 다시 새로운 대출에 쓸 수 있습니다.',
    keyPoints: ['증권화는 대출 자금의 순환을 빠르게 하지만, 원래 대출의 부실이 여러 투자자에게 퍼지는 통로가 되기도 한다고 설명돼요.', '2008년 세계금융위기에서 부실 주택담보대출을 묶은 증권의 부실이 널리 퍼진 사례가 다뤄져요.'],
    relatedConceptIds: ['mortgage', 'credit-risk', 'financial-crisis'],
    category: 'financial-products',
    sourceIds: ['bok-economic-history'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'digital-asset',
    title: '가상자산',
    shortDefinition: '블록체인 기술을 바탕으로 만들어진 디지털 형태의 자산이에요.',
    body: '가상자산(암호자산)은 비트코인처럼 블록체인 기술로 발행·거래되는 디지털 자산입니다. 국가가 가치를 보장하는 법정화폐와 달리, 가격이 수요와 공급에 따라 크게 오르내릴 수 있고, 보관·거래 방식도 기존 금융상품과 다릅니다.',
    keyPoints: ['가상자산은 다른 투자자산보다 가격 변동성이 큰 편으로 다뤄져요.', '지갑 보관·거래소 이용 과정에서 발생할 수 있는 보안·해킹 위험도 함께 고려할 부분이에요.'],
    caution: '가상자산은 예금자보호 대상이 아니며, 가치가 크게 떨어지거나 0에 가까워질 위험도 있다고 알려져 있어요.',
    relatedConceptIds: ['volatility', 'risk'],
    category: 'financial-products',
    sourceIds: ['fss-edu'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },

  // ══════════════════════════ 보험·연금·세금·절세계좌 ══════════════════════════
  {
    id: 'insurance-premium',
    title: '보험료',
    shortDefinition: '보험 계약을 유지하기 위해 정기적으로 내는 돈이에요.',
    body: '보험료는 보험 계약자가 보장을 받는 대가로 보험회사에 정기적으로 내는 돈입니다. 가입자의 나이, 보장 범위, 보험 기간 등에 따라 금액이 달라집니다.',
    keyPoints: ['보험료를 내지 못하는 기간이 길어지면 계약이 해지될 수 있어요.', '같은 보장이라도 상품·회사에 따라 보험료가 다를 수 있어요.'],
    relatedConceptIds: ['insurance-payout', 'protection-insurance'],
    category: 'insurance-pension-tax',
    sourceIds: ['fss-edu'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'insurance-payout',
    title: '보험금',
    shortDefinition: '보험에서 정한 사고나 상황이 생겼을 때 지급되는 돈이에요.',
    body: '보험금은 질병, 사고, 사망 등 보험 계약에서 정한 상황이 실제로 발생했을 때 보험회사가 지급하는 돈입니다. 보험료와 헷갈리기 쉽지만, 보험료는 "내는 돈", 보험금은 "받는 돈"이라는 점에서 반대의 개념입니다.',
    keyPoints: ['보험금을 받으려면 약관에서 정한 지급 조건을 충족해야 해요.', '가입 전에 어떤 경우에 보험금이 지급되는지 확인하는 것이 중요해요.'],
    relatedConceptIds: ['insurance-premium'],
    category: 'insurance-pension-tax',
    sourceIds: ['fss-edu'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'public-retirement-personal-pension',
    title: '국민연금·퇴직연금·개인연금',
    shortDefinition: '노후 소득을 준비하는 3가지 층으로, 각각 운영 주체와 성격이 달라요.',
    body: '국민연금은 국가가 운영하는 공적연금으로 소득에 따라 보험료를 내고 노후에 연금을 받습니다. 퇴직연금(DB·DC·IRP 등)은 회사가 근로자의 퇴직급여를 금융회사에 적립·운용하는 제도입니다. 개인연금(연금저축 등)은 개인이 스스로 가입해 준비하는 노후 자금입니다.\n\n2026년부터 국민연금 보험료율이 기존 9%에서 매년 0.5%포인트씩 단계적으로 올라 2033년 13%에 도달하도록 법이 개정되었고, 같은 해 소득대체율도 43%로 상향됩니다.',
    keyPoints: [
      '국민연금공단 사이트에서 내 예상 연금액을 확인해볼 수 있어요.',
      '퇴직연금이 DB형인지 DC형인지 확인해볼 수 있어요.',
    ],
    caution: '정확한 개인별 보험료·수급액은 국민연금공단에서 확인하는 것이 안전해요.',
    relatedConceptIds: ['pension-savings-and-irp'],
    category: 'insurance-pension-tax',
    sourceIds: ['nps-info'],
    reviewedAt: '2026-08-24',
    version: 2,
    status: 'reviewed',
  },
  {
    id: 'pension-savings-and-irp',
    title: '연금저축과 IRP',
    shortDefinition: '개인이 직접 가입해 노후자금을 모으면서, 납입액에 대해 세액공제를 받을 수 있는 계좌예요.',
    body: '연금저축과 개인형퇴직연금(IRP)은 개인이 스스로 가입해 노후자금을 적립하는 계좌로, 납입액에 대해 세액공제 혜택을 받을 수 있습니다. 국세청 기준으로 연금저축은 종합소득금액 4,500만원 이하일 때 600만원까지 15%, 초과 시 600만원까지 12% 세액공제를 받을 수 있고, IRP를 더해 합산 900만원까지 공제 한도가 늘어납니다.',
    keyPoints: [
      '올해 연금저축·IRP에 납입한 금액이 공제 한도(900만원) 안에 있는지 확인해볼 수 있어요.',
      '중도 인출 시 세제상 불이익이 있는지 가입한 금융회사에 확인해볼 수 있어요.',
    ],
    caution: '연금계좌는 중도에 찾으면 세제상 불이익이 있을 수 있어 장기 자금으로 접근하는 것이 일반적이에요. 정확한 한도·공제율은 매년 세법 개정으로 바뀔 수 있어요.',
    relatedConceptIds: ['public-retirement-personal-pension', 'financial-income-tax', 'tax-credit'],
    category: 'insurance-pension-tax',
    sourceIds: ['nts-pension-tax-credit'],
    reviewedAt: '2026-08-24',
    version: 2,
    status: 'reviewed',
  },
  {
    id: 'tax-credit',
    title: '세액공제',
    shortDefinition: '계산된 세금 자체에서 일정 금액을 그대로 깎아주는 제도예요.',
    body: '세액공제는 소득에 세율을 곱해 계산된 "세금" 자체에서 일정 금액이나 비율을 직접 빼주는 방식입니다. 연금저축·IRP 납입액처럼 정해진 항목에 대해 적용됩니다.',
    keyPoints: ['소득공제가 세금을 매기기 전 소득을 줄여주는 것이라면, 세액공제는 계산된 세금 자체를 줄여줘요.'],
    relatedConceptIds: ['income-deduction', 'pension-savings-and-irp'],
    category: 'insurance-pension-tax',
    sourceIds: ['nts-pension-tax-credit'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'income-deduction',
    title: '소득공제',
    shortDefinition: '세금을 매기기 전, 소득에서 일정 금액을 미리 빼주는 제도예요.',
    body: '소득공제는 세율을 곱하기 전 단계에서, 정해진 항목만큼 과세 대상 소득 자체를 줄여주는 방식입니다. 소득이 줄어든 만큼 그 소득에 매겨지는 세금도 함께 줄어드는 효과가 있습니다.',
    keyPoints: ['소득공제는 적용받는 사람의 세율 구간에 따라 실제로 줄어드는 세금 액수가 달라질 수 있어요.'],
    relatedConceptIds: ['tax-credit'],
    category: 'insurance-pension-tax',
    sourceIds: ['nts-financial-income-tax'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'financial-income-tax',
    title: '금융소득과 세금',
    shortDefinition: '이자·배당 같은 금융소득이 한 해 2,000만원을 넘으면, 다른 소득과 합쳐 세금을 계산해요.',
    body: '예금 이자, 채권 이자, 주식 배당 등을 금융소득이라고 합니다. 국세청 기준으로 금융소득이 연 2,000만원 이하이면 원천징수(소득세 14%+지방소득세)로 과세가 끝나지만, 2,000만원을 초과하면 초과분을 근로소득 등 다른 소득과 합산해 종합소득세로 신고해야 합니다.',
    keyPoints: ['한 해 예금 이자와 배당을 합친 금액이 2,000만원에 가까운지 확인해볼 수 있어요.'],
    caution: '구체적인 절세 방법은 개인 상황에 따라 달라 세무 전문가나 국세청 상담을 통해 확인하는 것이 안전해요.',
    relatedConceptIds: ['pension-savings-and-irp', 'tax-exemption'],
    category: 'insurance-pension-tax',
    sourceIds: ['nts-financial-income-tax'],
    reviewedAt: '2026-08-24',
    version: 2,
    status: 'reviewed',
  },
  {
    id: 'tax-exemption',
    title: '비과세',
    shortDefinition: '정해진 조건을 충족하면 아예 세금을 매기지 않는 것이에요.',
    body: '비과세는 특정 소득이나 상품에 대해 소득세 등을 아예 부과하지 않는 것을 말합니다. ISA의 일정 한도 내 수익, 일부 저축성 상품 등이 조건을 충족하면 비과세 혜택을 받을 수 있다고 알려져 있습니다.',
    keyPoints: ['비과세 조건은 상품과 시기에 따라 달라질 수 있어 가입 전 확인이 필요해요.'],
    relatedConceptIds: ['isa', 'financial-income-tax'],
    category: 'insurance-pension-tax',
    sourceIds: ['nts-financial-income-tax'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'isa',
    title: 'ISA',
    shortDefinition: '예금·펀드·주식 등을 한 계좌에 담아 세제 혜택을 받을 수 있는 개인종합자산관리계좌예요.',
    body: 'ISA(개인종합자산관리계좌)는 예금, 펀드, 주식 등 다양한 금융상품을 한 계좌에 담아 운용하면서, 일정 한도까지 발생한 이익에 비과세·분리과세 혜택을 받을 수 있는 계좌입니다. 가입 조건과 한도, 혜택 내용은 계좌 유형(일반형·서민형·농어민형 등)에 따라 다릅니다.',
    keyPoints: ['한 계좌 안에서 여러 상품에 나눠 투자할 수 있다는 점이 특징이에요.', '가입 유형별 정확한 한도·혜택은 세법 개정에 따라 달라질 수 있어요.'],
    relatedConceptIds: ['tax-exemption', 'pension-savings-and-irp'],
    category: 'insurance-pension-tax',
    sourceIds: ['nts-financial-income-tax'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  // ══════════════════════════ 시장과 경제지표 ══════════════════════════
  {
    id: 'gold-standard',
    title: '금본위제',
    shortDefinition: '화폐 가치를 정해진 양의 금과 연결해두는 화폐 제도예요.',
    body: '금본위제는 한 나라의 화폐 단위를 정해진 양의 금과 교환할 수 있도록 연결해둔 제도입니다. 화폐를 많이 찍어내려면 그만큼 금을 보유해야 해서, 통화량 조절에 제약이 있다는 특징이 있습니다. 19~20세기 여러 나라가 이 제도를 채택했다가 이후 대부분 벗어났습니다.',
    keyPoints: ['금 보유량이 통화량을 제약해, 정부가 경기 대응을 위해 화폐를 자유롭게 늘리기 어려웠다고 설명돼요.', '대공황 시기 여러 나라가 금본위제의 제약에서 벗어나는 선택을 했다고 다뤄져요.'],
    relatedConceptIds: ['central-bank', 'money-supply'],
    category: 'economy-market',
    sourceIds: ['bok-economic-history'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'reserve',
    title: '지급준비금',
    shortDefinition: '은행이 예금 인출 요청에 대비해 따로 보관해두는 돈이에요.',
    body: '지급준비금은 은행이 받은 예금 중 일부를 고객의 인출 요청에 대비해 대출하지 않고 남겨두는 돈입니다. 중앙은행이 정하는 지급준비율에 따라 은행이 남겨야 하는 최소 비율이 정해집니다.',
    keyPoints: ['지급준비율을 낮추면 은행이 대출에 쓸 수 있는 돈이 늘어나 통화량에 영향을 줄 수 있어요.'],
    relatedConceptIds: ['bank', 'central-bank', 'money-supply'],
    category: 'economy-market',
    sourceIds: ['bok-edu'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'great-depression',
    title: '대공황',
    shortDefinition: '1929년 미국에서 시작돼 1930년대 세계 경제를 크게 위축시킨 극심한 불황이에요.',
    body: '대공황은 1929년 미국 주식시장 붕괴를 시작으로 1930년대 내내 이어진, 20세기 최대 규모의 경제 불황입니다. 은행 줄도산, 대량 실업, 물가 하락(디플레이션)이 함께 나타났고 그 충격이 세계 여러 나라로 번졌습니다.',
    keyPoints: ['은행이 잇따라 문을 닫으면서 예금자들의 신뢰가 크게 흔들렸다고 설명돼요.', '이 사건 이후 여러 나라에서 예금자보호제도, 중앙은행의 역할 확대 등 제도적 변화가 뒤따랐어요.'],
    relatedConceptIds: ['recession', 'unemployment', 'deflation', 'fiscal-policy'],
    category: 'economy-market',
    sourceIds: ['bok-economic-history'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'central-bank',
    title: '중앙은행',
    shortDefinition: '한 나라의 화폐를 발행하고 통화정책을 담당하는 은행이에요.',
    body: '중앙은행은 화폐 발행, 기준금리 결정, 금융 시스템 안정 관리 등을 맡는 특별한 은행입니다. 한국은 한국은행, 미국은 연방준비제도(Fed)가 이 역할을 합니다. 일반 은행과 달리 이윤을 목적으로 하지 않고 물가 안정 등 정책 목표를 위해 움직입니다.',
    keyPoints: ['중앙은행의 대표적인 정책 수단이 기준금리예요.', '금융위기 상황에서 시중에 자금을 공급하는 최종 대부자 역할을 하기도 해요.'],
    relatedConceptIds: ['base-rate', 'money-supply', 'financial-stability'],
    category: 'economy-market',
    sourceIds: ['bok-edu'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'financial-stability',
    title: '금융안정',
    shortDefinition: '금융 시스템이 큰 충격 없이 제 기능을 계속할 수 있는 상태예요.',
    body: '금융안정은 은행·시장 같은 금융 시스템이 큰 위기 없이 자금 중개, 결제 같은 본연의 기능을 원활히 수행하는 상태를 말합니다. 중앙은행과 금융당국의 중요한 정책 목표 중 하나로 다뤄집니다.',
    keyPoints: ['한 금융회사의 부실이 다른 금융회사로 번지는 것을 막는 것도 금융안정의 중요한 부분이에요.'],
    relatedConceptIds: ['central-bank', 'financial-crisis'],
    category: 'economy-market',
    sourceIds: ['bok-edu'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'economic-growth-rate',
    title: '경제성장률과 국내총생산(GDP)',
    shortDefinition: '국내총생산(GDP)은 한 나라에서 일정 기간 만들어진 재화·서비스 가치의 합이고, 경제성장률은 그 규모가 늘어난 비율이에요.',
    body: '국내총생산(GDP)은 한 나라 안에서 일정 기간(보통 1년 또는 분기) 새로 생산된 재화와 서비스의 가치를 모두 더한 지표입니다. 경제성장률은 이 GDP가 이전 기간보다 얼마나 늘었는지를 비율로 나타낸 것으로, 한 나라 경제 규모가 커지는 속도를 가늠하는 대표 지표로 쓰입니다.',
    keyPoints: ['성장률이 플러스라고 모든 사람의 삶이 나아졌다는 뜻은 아니고, 분배 상황은 별도로 살펴봐야 해요.', '성장률이 마이너스로 여러 분기 이어지면 경기침체로 볼 수 있어요.'],
    relatedConceptIds: ['recession', 'unemployment'],
    category: 'economy-market',
    sourceIds: ['kostat-info', 'bok-ecos'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'recession',
    title: '경기침체',
    shortDefinition: '경제 활동이 상당 기간 위축되는 상황이에요.',
    body: '경기침체는 생산, 소비, 고용 등 경제 전반의 활동이 일정 기간 이상 위축되는 상황을 말합니다. 흔히 국내총생산 성장률이 여러 분기 연속 마이너스를 기록하는 것을 하나의 참고 기준으로 삼습니다.',
    keyPoints: ['경기는 좋아졌다 나빠지기를 반복하는 경기순환의 한 국면으로 다뤄져요.', '경기침체기에는 실업률이 오르고 기업 투자가 줄어드는 경향이 있다고 설명돼요.'],
    relatedConceptIds: ['economic-growth-rate', 'unemployment', 'fiscal-policy'],
    category: 'economy-market',
    sourceIds: ['bok-edu'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'unemployment',
    title: '실업과 실업률',
    shortDefinition: '일할 능력과 의사가 있는데 일자리를 구하지 못한 상태이고, 실업률은 그 비율이에요.',
    body: '실업은 일할 능력과 의사가 있는 사람이 일자리를 구하지 못한 상태를 말합니다. 실업률은 경제활동인구(일할 능력과 의사가 있는 사람) 중 실업 상태인 사람의 비율로, 통계청이 정기적으로 집계해 발표합니다.',
    keyPoints: ['경기침체기에는 실업률이 오르는 경향이 있다고 설명돼요.', '통계상 실업률과 체감 고용 상황이 다르게 느껴질 수 있어요.'],
    relatedConceptIds: ['recession', 'fiscal-policy'],
    category: 'economy-market',
    sourceIds: ['kostat-info'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'fiscal-policy',
    title: '재정정책',
    shortDefinition: '정부가 세금을 걷고 예산을 쓰는 방식으로 경제에 영향을 주는 정책이에요.',
    body: '재정정책은 정부가 세금(수입)과 정부지출(지출)을 조절해 경기와 소득 분배 등에 영향을 미치는 정책입니다. 경기가 나쁠 때 정부지출을 늘리거나 세금을 줄여 수요를 뒷받침하는 방식이 대표적으로 다뤄집니다.',
    keyPoints: ['중앙은행의 통화정책과 함께 경제를 조절하는 대표적인 두 축으로 다뤄져요.', '정부지출 확대는 재정적자·국가부채 증가로 이어질 수 있다는 점도 함께 논의돼요.'],
    relatedConceptIds: ['aggregate-demand', 'government-bond', 'monetary-policy'],
    category: 'economy-market',
    sourceIds: ['bok-edu'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'monetary-policy',
    title: '통화정책',
    shortDefinition: '중앙은행이 금리나 통화량을 조절해 물가와 경기에 영향을 주는 정책이에요.',
    body: '통화정책은 중앙은행이 기준금리 조정이나 시중 자금 공급량 조절 등을 통해 물가와 경기에 영향을 미치는 정책입니다. 재정정책이 정부의 예산으로 움직인다면, 통화정책은 중앙은행이 금리·통화량으로 움직인다는 점이 다릅니다.',
    keyPoints: ['물가가 많이 오를 때는 금리를 올리는 긴축적 통화정책을, 경기가 부진할 때는 금리를 낮추는 완화적 통화정책을 쓰는 경우가 많다고 설명돼요.'],
    relatedConceptIds: ['central-bank', 'base-rate', 'fiscal-policy'],
    category: 'economy-market',
    sourceIds: ['bok-edu'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'aggregate-demand',
    title: '총수요',
    shortDefinition: '한 경제 안에서 소비·투자·정부지출·수출 등을 모두 더한 수요예요.',
    body: '총수요는 가계 소비, 기업 투자, 정부지출, 순수출(수출-수입)을 모두 더한, 한 경제 전체의 수요 규모입니다. 총수요가 크게 줄면 생산과 고용이 위축되는 경기침체로 이어질 수 있다고 설명됩니다.',
    keyPoints: ['정부는 재정정책·통화정책으로 총수요에 영향을 주려고 해요.'],
    relatedConceptIds: ['fiscal-policy', 'recession'],
    category: 'economy-market',
    sourceIds: ['bok-edu'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'government-bond',
    title: '국채',
    shortDefinition: '국가가 돈을 빌리기 위해 발행하는 채권이에요.',
    body: '국채는 정부가 재정 자금을 마련하기 위해 발행하는 채권입니다. 투자자는 정부에 돈을 빌려주고 정해진 이자와 만기 상환을 약속받습니다. 국채 금리는 국가의 재정 상태나 신용도에 대한 시장의 평가를 반영한다고 여겨집니다.',
    keyPoints: ['국채가 많이 발행될수록 국가부채가 늘어나는 결과로 이어질 수 있어요.', '국채 금리가 오르면 정부가 새로 돈을 빌릴 때 내야 하는 이자 비용도 늘어나요.'],
    relatedConceptIds: ['national-debt', 'fiscal-policy'],
    category: 'economy-market',
    sourceIds: ['bok-edu'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'national-debt',
    title: '국가부채',
    shortDefinition: '정부가 국채 발행 등으로 지고 있는 빚의 총액이에요.',
    body: '국가부채는 정부가 국채 발행이나 차입 등으로 지고 있는 빚 전체를 말합니다. 국가부채 자체보다는 그 나라 경제 규모(GDP) 대비 비율로 비교하는 경우가 많습니다.',
    keyPoints: ['국가부채가 많다고 무조건 위험한 것은 아니며, 상환 능력과 부채의 용도 등을 함께 봐야 한다고 설명돼요.'],
    relatedConceptIds: ['government-bond', 'fiscal-policy'],
    category: 'economy-market',
    sourceIds: ['bok-edu'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'financial-crisis',
    title: '금융위기',
    shortDefinition: '금융 시스템의 신뢰나 유동성이 흔들려 경제 전반에 큰 충격을 주는 상황이에요.',
    body: '금융위기는 은행 등 금융회사의 부실, 신뢰 상실, 자금 경색 등으로 금융 시스템이 제 기능을 하지 못하고 그 충격이 실물경제까지 번지는 상황을 말합니다. 한 기관·시장의 문제가 연결망을 통해 다른 곳으로 확산되며 커지는 경우가 많다고 설명됩니다.',
    keyPoints: ['금융위기는 종종 자산가격 급락, 신용경색, 실업 증가를 동반해요.', '위기 이후에는 통화정책·재정정책을 동원한 대응이 뒤따르는 경우가 많아요.'],
    relatedConceptIds: ['financial-stability', 'quantitative-easing'],
    category: 'economy-market',
    sourceIds: ['bok-edu'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },
  {
    id: 'quantitative-easing',
    title: '양적완화',
    shortDefinition: '중앙은행이 국채 등을 대규모로 사들여 시중에 돈을 푸는 정책이에요.',
    body: '양적완화(QE)는 기준금리를 더 낮추기 어려운 상황에서, 중앙은행이 국채 등 자산을 대규모로 사들여 시중에 직접 돈을 공급하는 정책입니다. 2008년 금융위기 이후 여러 나라 중앙은행이 사용하며 널리 알려졌습니다.',
    keyPoints: ['시중에 유동성을 늘려 대출·투자를 촉진하려는 목적으로 설명돼요.', '통화량이 크게 늘어난 만큼 물가 상승 압력에 대한 논쟁도 함께 따라와요.'],
    relatedConceptIds: ['central-bank', 'money-supply', 'financial-crisis'],
    category: 'economy-market',
    sourceIds: ['bok-edu'],
    reviewedAt: '2026-08-24',
    version: 1,
    status: 'reviewed',
  },

  // ══════════════════ 검토 중(제목만 확정, 상세 내용은 검증 후 추가) ══════════════════
  ...([
    ['oil-shock', '오일쇼크', 'economy-market'],
    ['equal-principal-and-interest', '원리금균등상환', 'debt-credit'],
    ['equal-principal', '원금균등상환', 'debt-credit'],
    ['bullet-repayment', '만기일시상환', 'debt-credit'],
    ['downside-risk', '손실 가능성', 'investing'],
    ['compound-return', '복리수익', 'investing'],
    ['rebalancing', '리밸런싱', 'investing'],
    ['market-cap', '시가총액', 'financial-products'],
    ['stock-index', '주가지수', 'financial-products'],
    ['commodity', '원자재', 'financial-products'],
    ['foreign-currency-asset', '외화자산', 'financial-products'],
    ['fund-distribution', '분배금', 'financial-products'],
    ['protection-insurance', '보장성 보험', 'insurance-pension-tax'],
    ['savings-insurance', '저축성 보험', 'insurance-pension-tax'],
    ['renewable-insurance', '갱신형', 'insurance-pension-tax'],
    ['non-renewable-insurance', '비갱신형', 'insurance-pension-tax'],
    ['waiting-period', '면책기간', 'insurance-pension-tax'],
    ['reduction-period', '감액기간', 'insurance-pension-tax'],
    ['surrender-value', '해지환급금', 'insurance-pension-tax'],
    ['tax-deferral', '과세이연', 'insurance-pension-tax'],
    ['gain-loss-offset', '손익통산', 'insurance-pension-tax'],
    ['business-cycle', '경기순환', 'economy-market'],
    ['fiscal-deficit', '재정적자', 'economy-market'],
    ['trade-balance', '무역수지', 'economy-market'],
    ['foreign-reserves', '외환보유액', 'economy-market'],
    ['asset-bubble', '자산 거품', 'economy-market'],
  ] as const).map(([id, title, category]) => ({
    id,
    title,
    shortDefinition: '',
    body: '',
    keyPoints: [],
    relatedConceptIds: [],
    category,
    sourceIds: [],
    reviewedAt: '',
    version: 1,
    status: 'in_review' as const,
  })),
]

export const CONCEPT_CATEGORY_LABEL: Record<string, string> = {
  'daily-finance': '생활경제',
  'money-interest': '금리·물가·통화',
  'debt-credit': '부채·신용',
  investing: '투자',
  'financial-products': '금융상품',
  'insurance-pension-tax': '보험·연금·세금',
  'economy-market': '시장·경제',
}
