import type { CurriculumModule, LearningContent } from '../types/models'

// 13개 과정. 순서가 나중에 바뀌더라도 진행 기록은 order가 아니라 id를 기준으로
// 유지되므로(§3), 이 배열의 순서를 바꿔도 사용자 진행 상태는 깨지지 않는다.
export const CURRICULUM_MODULES: CurriculumModule[] = [
  {
    id: 'money-flow',
    order: 1,
    title: '내 돈의 흐름',
    description: '수입과 지출, 저축률을 통해 돈의 흐름을 이해해요.',
    estimatedMinutes: 6,
    itemIds: ['money-flow-concept', 'money-flow-calculator'],
    relatedAssetTypes: [],
  },
  {
    id: 'emergency-fund',
    order: 2,
    title: '비상금',
    description: '예상하지 못한 상황에 대비하는 자금의 역할을 알아봐요.',
    estimatedMinutes: 4,
    itemIds: ['emergency-fund-concept'],
    relatedAssetTypes: ['cash_deposit'],
  },
  {
    id: 'interest-compound',
    order: 3,
    title: '금리와 복리',
    description: '금리와 시간이 돈의 가치에 미치는 영향을 알아봐요.',
    estimatedMinutes: 8,
    itemIds: ['interest-compound-concept', 'interest-compound-calculator', 'interest-compound-quiz'],
    relatedAssetTypes: ['cash_deposit', 'savings'],
  },
  {
    id: 'inflation',
    order: 4,
    title: '물가와 구매력',
    description: '물가가 현재와 미래의 구매력에 미치는 영향을 알아봐요.',
    estimatedMinutes: 8,
    itemIds: ['inflation-concept', 'inflation-calculator', 'inflation-quiz'],
    relatedAssetTypes: ['cash_deposit'],
  },
  {
    id: 'debt-loans',
    order: 5,
    title: '대출과 부채',
    description: '대출이자와 상환 방식, 부채 관리의 기본을 알아봐요.',
    estimatedMinutes: 5,
    itemIds: ['debt-loans-concept'],
    relatedAssetTypes: ['debt'],
  },
  {
    id: 'investment-basics',
    order: 6,
    title: '투자 기초',
    description: '수익률, 손실 가능성, 변동성과 분산의 의미를 알아봐요.',
    estimatedMinutes: 9,
    itemIds: ['investment-basics-concept-1', 'investment-basics-concept-2', 'investment-basics-concept-3'],
    relatedAssetTypes: ['domestic_stock', 'foreign_stock', 'etf'],
  },
  {
    id: 'stocks-etf',
    order: 7,
    title: '주식과 ETF',
    description: '주식과 ETF의 구조와 주요 차이를 알아봐요.',
    estimatedMinutes: 5,
    itemIds: ['stocks-etf-concept'],
    relatedAssetTypes: ['domestic_stock', 'foreign_stock', 'etf'],
  },
  {
    id: 'bonds',
    order: 8,
    title: '채권',
    description: '채권의 이자, 만기, 금리와 가격의 관계를 알아봐요.',
    estimatedMinutes: 5,
    itemIds: [],
    relatedAssetTypes: ['bond'],
  },
  {
    id: 'insurance',
    order: 9,
    title: '보험',
    description: '보험의 목적과 가입 전에 확인할 항목을 알아봐요.',
    estimatedMinutes: 5,
    itemIds: [],
  },
  {
    id: 'tax',
    order: 10,
    title: '세금',
    description: '소득과 금융생활에서 세금이 발생하는 시점을 알아봐요.',
    estimatedMinutes: 5,
    itemIds: ['tax-concept'],
  },
  {
    id: 'pension-isa',
    order: 11,
    title: '연금과 ISA',
    description: '장기 자산관리 계좌의 목적과 기본 구조를 알아봐요.',
    estimatedMinutes: 7,
    itemIds: ['pension-isa-concept-1', 'pension-isa-concept-2'],
    relatedAssetTypes: ['pension'],
  },
  {
    id: 'digital-assets',
    order: 12,
    title: '가상자산',
    description: '가상자산의 구조와 변동성, 보관 위험을 알아봐요.',
    estimatedMinutes: 5,
    itemIds: [],
    relatedAssetTypes: ['crypto'],
  },
  {
    id: 'asset-review',
    order: 13,
    title: '자산 점검',
    description: '배운 내용을 바탕으로 내 자산 구성을 점검해요.',
    estimatedMinutes: 6,
    itemIds: ['asset-review-calculator', 'asset-review-checklist'],
  },
]

const BOK_SOURCE = {
  sourceName: '한국은행 경제교육',
  sourceUrl: 'https://www.bok.or.kr/portal/main/contents.do?menuNo=200583',
}

// 실제 검증된 금융 콘텐츠가 있는 10개 과정만 항목을 채운다. 채권·보험·가상자산은
// 대응하는 검수된 개념 카드가 아직 없어 itemIds를 비워 "준비 중"으로 남긴다(§14).
export const LEARNING_CONTENTS: LearningContent[] = [
  // ── 내 돈의 흐름 ──────────────────────────────────────────────
  {
    id: 'money-flow-concept',
    curriculumId: 'money-flow',
    type: 'concept',
    title: '저축률 개념 알아보기',
    body: '',
    required: true,
    order: 1,
    version: 1,
    reviewedAt: '2026-08-24',
    linkedConceptId: 'savings-rate',
  },
  {
    id: 'money-flow-calculator',
    curriculumId: 'money-flow',
    type: 'calculator',
    title: '저축률 계산기로 확인하기',
    body: '',
    required: true,
    order: 2,
    version: 1,
    reviewedAt: '2026-08-24',
    linkedCalculatorId: 'savings_rate',
  },

  // ── 비상금 ────────────────────────────────────────────────────
  {
    id: 'emergency-fund-concept',
    curriculumId: 'emergency-fund',
    type: 'concept',
    title: '비상자금 개념 알아보기',
    body: '',
    required: true,
    order: 1,
    version: 1,
    reviewedAt: '2026-08-24',
    linkedConceptId: 'emergency-fund',
  },

  // ── 금리와 복리 ───────────────────────────────────────────────
  {
    id: 'interest-compound-concept',
    curriculumId: 'interest-compound',
    type: 'concept',
    title: '금리와 복리 알아보기',
    body: '',
    required: true,
    order: 1,
    version: 1,
    reviewedAt: '2026-08-24',
    linkedConceptId: 'simple-vs-compound-interest',
  },
  {
    id: 'interest-compound-calculator',
    curriculumId: 'interest-compound',
    type: 'calculator',
    title: '복리 계산기로 확인하기',
    body: '',
    required: true,
    order: 2,
    version: 1,
    reviewedAt: '2026-08-24',
    linkedCalculatorId: 'compound_interest',
  },
  {
    id: 'interest-compound-quiz',
    curriculumId: 'interest-compound',
    type: 'quiz',
    title: '이해했는지 확인하기',
    body: '',
    required: true,
    order: 3,
    version: 1,
    reviewedAt: '2026-08-24',
    ...BOK_SOURCE,
    quiz: {
      question: '단리와 복리의 가장 큰 차이는 무엇인가요?',
      choices: [
        '단리는 원금에만 이자가 붙고, 복리는 이미 붙은 이자에도 다시 이자가 붙는다',
        '단리가 항상 복리보다 더 많은 이자를 준다',
        '복리는 예금·적금에는 적용되지 않는다',
        '단리와 복리는 계산 방식이 같다',
      ],
      correctIndex: 0,
      explanation:
        '단리는 원금에만 이자가 계산되고, 복리는 원금과 그동안 붙은 이자에도 다시 이자가 붙는 방식이에요. 그래서 기간이 길어질수록 단리와 복리의 차이가 커질 수 있어요.',
    },
  },

  // ── 물가와 구매력 ─────────────────────────────────────────────
  {
    id: 'inflation-concept',
    curriculumId: 'inflation',
    type: 'concept',
    title: '물가와 구매력 알아보기',
    body: '',
    required: true,
    order: 1,
    version: 1,
    reviewedAt: '2026-08-24',
    linkedConceptId: 'inflation-and-purchasing-power',
  },
  {
    id: 'inflation-calculator',
    curriculumId: 'inflation',
    type: 'calculator',
    title: '물가 반영 계산기로 확인하기',
    body: '',
    required: true,
    order: 2,
    version: 1,
    reviewedAt: '2026-08-24',
    linkedCalculatorId: 'inflation_adjusted',
  },
  {
    id: 'inflation-quiz',
    curriculumId: 'inflation',
    type: 'quiz',
    title: '이해했는지 확인하기',
    body: '',
    required: true,
    order: 3,
    version: 1,
    reviewedAt: '2026-08-24',
    ...BOK_SOURCE,
    quiz: {
      question: '물가가 오르면 지금 가지고 있는 현금의 실질 구매력은 어떻게 되나요?',
      choices: [
        '구매력이 줄어든다',
        '구매력이 항상 늘어난다',
        '물가와 구매력은 서로 관계가 없다',
        '현금은 물가의 영향을 받지 않는다',
      ],
      correctIndex: 0,
      explanation:
        '물가가 오르면 같은 금액으로 살 수 있는 양이 줄어들어요. 이걸 "구매력이 줄었다"고 표현해요. 그래서 현금을 그대로 오래 들고 있으면 실질 가치가 점점 줄어들 수 있어요.',
    },
  },

  // ── 대출과 부채 ───────────────────────────────────────────────
  {
    id: 'debt-loans-concept',
    curriculumId: 'debt-loans',
    type: 'concept',
    title: '대출금리와 상환방식 알아보기',
    body: '',
    required: true,
    order: 1,
    version: 1,
    reviewedAt: '2026-08-24',
    linkedConceptId: 'loan-rate-and-repayment',
  },

  // ── 투자 기초 ─────────────────────────────────────────────────
  {
    id: 'investment-basics-concept-1',
    curriculumId: 'investment-basics',
    type: 'concept',
    title: '수익률과 원금 회복률 알아보기',
    body: '',
    required: true,
    order: 1,
    version: 1,
    reviewedAt: '2026-08-24',
    linkedConceptId: 'return-and-breakeven',
  },
  {
    id: 'investment-basics-concept-2',
    curriculumId: 'investment-basics',
    type: 'concept',
    title: '분산투자 알아보기',
    body: '',
    required: true,
    order: 2,
    version: 1,
    reviewedAt: '2026-08-24',
    linkedConceptId: 'diversification',
  },
  {
    id: 'investment-basics-concept-3',
    curriculumId: 'investment-basics',
    type: 'concept',
    title: '투자기간과 변동성 알아보기',
    body: '',
    required: true,
    order: 3,
    version: 1,
    reviewedAt: '2026-08-24',
    linkedConceptId: 'investment-horizon-and-volatility',
  },

  // ── 주식과 ETF ────────────────────────────────────────────────
  {
    id: 'stocks-etf-concept',
    curriculumId: 'stocks-etf',
    type: 'concept',
    title: '주식·채권·ETF의 차이 알아보기',
    body: '',
    required: true,
    order: 1,
    version: 1,
    reviewedAt: '2026-08-24',
    linkedConceptId: 'stocks-bonds-etfs',
  },

  // ── 세금 ──────────────────────────────────────────────────────
  {
    id: 'tax-concept',
    curriculumId: 'tax',
    type: 'concept',
    title: '금융소득과 세금 알아보기',
    body: '',
    required: true,
    order: 1,
    version: 1,
    reviewedAt: '2026-08-24',
    linkedConceptId: 'financial-income-tax',
  },

  // ── 연금과 ISA ────────────────────────────────────────────────
  {
    id: 'pension-isa-concept-1',
    curriculumId: 'pension-isa',
    type: 'concept',
    title: '국민연금·퇴직연금·개인연금 알아보기',
    body: '',
    required: true,
    order: 1,
    version: 1,
    reviewedAt: '2026-08-24',
    linkedConceptId: 'public-retirement-personal-pension',
  },
  {
    id: 'pension-isa-concept-2',
    curriculumId: 'pension-isa',
    type: 'concept',
    title: '연금저축과 IRP 알아보기',
    body: '',
    required: true,
    order: 2,
    version: 1,
    reviewedAt: '2026-08-24',
    linkedConceptId: 'pension-savings-and-irp',
  },

  // ── 자산 점검 ─────────────────────────────────────────────────
  {
    id: 'asset-review-calculator',
    curriculumId: 'asset-review',
    type: 'calculator',
    title: '목표저축 계산기로 확인하기',
    body: '',
    required: true,
    order: 1,
    version: 1,
    reviewedAt: '2026-08-24',
    linkedCalculatorId: 'goal_savings',
  },
  {
    id: 'asset-review-checklist',
    curriculumId: 'asset-review',
    type: 'checklist',
    title: '자산 점검 체크리스트',
    body: '',
    required: true,
    order: 2,
    version: 1,
    reviewedAt: '2026-08-24',
    checklistItems: [
      '자산 현황 화면에서 내 자산 구성(현금·예적금·투자·연금 등)을 확인했어요',
      '목표저축 계산기로 목표 금액 하나와 예상 저축 기간을 계산해봤어요',
      '지금 저축·투자 비중이 내 목표와 맞는지 스스로 점검해봤어요',
    ],
  },
]
