import type { LearningSource } from '../types/models'

// 돈 개념 사전과 차근차근 경제사가 공통으로 참조하는 출처 카탈로그.
// 개별 카드/모듈은 이 목록의 id만 참조한다(§17 — 출처 내용을 복제하지 않는다).
export const LEARNING_SOURCES: LearningSource[] = [
  {
    id: 'fss-edu',
    name: 'e-금융교육센터',
    publisher: '금융감독원',
    url: 'https://www.fss.or.kr/edu/main/main.do',
    reviewedAt: '2026-08-24',
    sourceType: 'official',
  },
  {
    id: 'bok-edu',
    name: '경제교육',
    publisher: '한국은행',
    url: 'https://www.bok.or.kr/portal/main/contents.do?menuNo=200583',
    reviewedAt: '2026-08-24',
    sourceType: 'official',
  },
  {
    id: 'bok-ecos',
    name: '경제통계시스템(ECOS)',
    publisher: '한국은행',
    url: 'https://ecos.bok.or.kr',
    reviewedAt: '2026-08-24',
    sourceType: 'official',
  },
  {
    id: 'nts-pension-tax-credit',
    name: '연금계좌 세액공제',
    publisher: '국세청',
    url: 'https://www.nts.go.kr/nts/cm/cntnts/cntntsView.do?cntntsId=7875',
    reviewedAt: '2026-08-24',
    sourceType: 'official',
  },
  {
    id: 'nts-financial-income-tax',
    name: '금융소득 - 자주묻는 Q&A',
    publisher: '국세청',
    url: 'https://call.nts.go.kr/call/qna/selectQnaInfo.do?mi=1441&ctgId=CTG11775',
    reviewedAt: '2026-08-24',
    sourceType: 'official',
  },
  {
    id: 'nps-info',
    name: '국민연금 보험료율 및 제도 안내',
    publisher: '국민연금공단',
    url: 'https://www.nps.or.kr/pnsinfo/ntpsklg/getOHAF0104M0.do',
    reviewedAt: '2026-08-24',
    sourceType: 'official',
  },
  {
    id: 'kdic-info',
    name: '예금자보호제도',
    publisher: '예금보험공사',
    url: 'https://www.kdic.or.kr/protect/system01.do',
    reviewedAt: '2026-08-24',
    sourceType: 'official',
  },
  {
    id: 'kostat-info',
    name: '국가통계포털(KOSIS)',
    publisher: '통계청',
    url: 'https://kosis.kr',
    reviewedAt: '2026-08-24',
    sourceType: 'official',
  },
  {
    id: 'bok-economic-history',
    name: '알기 쉬운 경제이야기 · 화폐금융박물관 자료',
    publisher: '한국은행',
    url: 'https://www.bok.or.kr/portal/bbs/P0000538/list.do?menuNo=200147',
    reviewedAt: '2026-08-24',
    sourceType: 'official',
  },
  {
    id: 'fss-financial-history',
    name: '금융용어사전 · 금융과 경제 이야기',
    publisher: '금융감독원',
    url: 'https://www.fss.or.kr/edu/main/main.do',
    reviewedAt: '2026-08-24',
    sourceType: 'official',
  },
  {
    id: 'hf-repayment',
    name: '월별상환원리금(대출 상환방식 안내)',
    publisher: '한국주택금융공사',
    url: 'https://www.hf.go.kr/ko/sub01/sub01_06_03.do',
    reviewedAt: '2026-08-24',
    sourceType: 'official',
  },
  {
    id: 'nara-index-marketcap',
    name: 'e-나라지표 · 상장회사수 및 시가총액',
    publisher: '통계청',
    url: 'https://www.index.go.kr/unity/potal/main/EachDtlPageDetail.do?idx_cd=1079',
    reviewedAt: '2026-08-24',
    sourceType: 'official',
  },
  {
    id: 'nara-index-stockindex',
    name: 'e-나라지표 · 주가지수',
    publisher: '통계청',
    url: 'https://www.index.go.kr/unity/potal/main/EachDtlPageDetail.do?idx_cd=1080',
    reviewedAt: '2026-08-24',
    sourceType: 'official',
  },
  {
    id: 'krx-kind',
    name: '전자공시시스템(KIND)',
    publisher: '한국거래소',
    url: 'https://kind.krx.co.kr',
    reviewedAt: '2026-08-24',
    sourceType: 'official',
  },
  {
    id: 'bok-fx-reserves',
    name: '외환보유액의 의의',
    publisher: '한국은행',
    url: 'https://www.bok.or.kr/portal/main/contents.do?menuNo=200411',
    reviewedAt: '2026-08-24',
    sourceType: 'official',
  },
  {
    id: 'moef-fiscal-balance',
    name: '시사경제용어사전 · 재정수지',
    publisher: '기획재정부',
    url: 'https://mofe.go.kr/sisa/dictionary/detail?idx=2169',
    reviewedAt: '2026-08-24',
    sourceType: 'official',
  },
  {
    id: 'moef-balance-of-payments',
    name: '시사경제용어사전 · 국제수지',
    publisher: '기획재정부',
    url: 'https://mofe.go.kr/sisa/dictionary/detail?idx=587',
    reviewedAt: '2026-08-24',
    sourceType: 'official',
  },
  {
    id: 'kosis-business-cycle',
    name: '경기순환시계',
    publisher: '통계청',
    url: 'https://kosis.kr/visual/bcc/index/index.do?mb=N',
    reviewedAt: '2026-08-24',
    sourceType: 'official',
  },
  {
    id: 'history-go-kr-oil-shock',
    name: '우리역사넷 · 오일쇼크',
    publisher: '국사편찬위원회',
    url: 'https://contents.history.go.kr/mobile/kc/view.do?levelId=kc_i500270&code=kc_age_50',
    reviewedAt: '2026-08-24',
    sourceType: 'official',
  },
  {
    id: 'fss-insurance-terms',
    name: '자주 쓰이는 보험용어',
    publisher: '금융감독원',
    url: 'https://law.fss.or.kr/main/prc/is/sub/is004.jsp?menuNo=900392',
    reviewedAt: '2026-08-24',
    sourceType: 'official',
  },
  {
    id: 'knia-dictionary',
    name: '보험용어사전',
    publisher: '손해보험협회',
    url: 'https://www.knia.or.kr/howtouse/dictionary',
    reviewedAt: '2026-08-24',
    sourceType: 'official',
  },
  {
    id: 'nts-gain-loss-offset',
    name: '금융투자소득 손익통산 관련 안내',
    publisher: '국세청',
    url: 'https://www.nts.go.kr/nts/cm/cntnts/cntntsView.do?cntntsId=8800&mi=12274',
    reviewedAt: '2026-08-24',
    sourceType: 'official',
  },
]
