import type { LearningSource } from '../types/models'

// 돈 개념 사전과 차근차근 경제사가 공통으로 참조하는 출처 카탈로그.
// 개별 카드/모듈은 이 목록의 id만 참조한다(§17 — 출처 내용을 복제하지 않는다).
export const LEARNING_SOURCES: LearningSource[] = [
  {
    id: 'fss-edu',
    name: 'e-금융교육센터',
    publisher: '금융감독원',
    url: 'https://www.fss.or.kr/edu/main/main.do',
    reviewedAt: '2026-08-24',
    sourceType: 'official',
  },
  {
    id: 'bok-edu',
    name: '경제교육',
    publisher: '한국은행',
    url: 'https://www.bok.or.kr/portal/main/contents.do?menuNo=200583',
    reviewedAt: '2026-08-24',
    sourceType: 'official',
  },
  {
    id: 'bok-ecos',
    name: '경제통계시스템(ECOS)',
    publisher: '한국은행',
    url: 'https://ecos.bok.or.kr',
    reviewedAt: '2026-08-24',
    sourceType: 'official',
  },
  {
    id: 'nts-pension-tax-credit',
    name: '연금계좌 세액공제',
    publisher: '국세청',
    url: 'https://www.nts.go.kr/nts/cm/cntnts/cntntsView.do?cntntsId=7875',
    reviewedAt: '2026-08-24',
    sourceType: 'official',
  },
  {
    id: 'nts-financial-income-tax',
    name: '금융소득 - 자주묻는 Q&A',
    publisher: '국세청',
    url: 'https://call.nts.go.kr/call/qna/selectQnaInfo.do?mi=1441&ctgId=CTG11775',
    reviewedAt: '2026-08-24',
    sourceType: 'official',
  },
  {
    id: 'nps-info',
    name: '국민연금 보험료율 및 제도 안내',
    publisher: '국민연금공단',
    url: 'https://www.nps.or.kr/pnsinfo/ntpsklg/getOHAF0104M0.do',
    reviewedAt: '2026-08-24',
    sourceType: 'official',
  },
  {
    id: 'kdic-info',
    name: '예금자보호제도',
    publisher: '예금보험공사',
    url: 'https://www.kdic.or.kr/protect/system01.do',
    reviewedAt: '2026-08-24',
    sourceType: 'official',
  },
  {
    id: 'kostat-info',
    name: '국가통계포털(KOSIS)',
    publisher: '통계청',
    url: 'https://kosis.kr',
    reviewedAt: '2026-08-24',
    sourceType: 'official',
  },
  {
    id: 'bok-economic-history',
    name: '알기 쉬운 경제이야기 · 화폐금융박물관 자료',
    publisher: '한국은행',
    url: 'https://www.bok.or.kr/portal/bbs/P0000538/list.do?menuNo=200147',
    reviewedAt: '2026-08-24',
    sourceType: 'official',
  },
  {
    id: 'fss-financial-history',
    name: '금융용어사전 · 금융과 경제 이야기',
    publisher: '금융감독원',
    url: 'https://www.fss.or.kr/edu/main/main.do',
    reviewedAt: '2026-08-24',
    sourceType: 'official',
  },
  {
    id: 'hf-repayment',
    name: '월별상환원리금(대출 상환방식 안내)',
    publisher: '한국주택금융공사',
    url: 'https://www.hf.go.kr/ko/sub01/sub01_06_03.do',
    reviewedAt: '2026-08-24',
    sourceType: 'official',
  },
  {
    id: 'nara-index-marketcap',
    name: 'e-나라지표 · 상장회사수 및 시가총액',
    publisher: '통계청',
    url: 'https://www.index.go.kr/unity/potal/main/EachDtlPageDetail.do?idx_cd=1079',
    reviewedAt: '2026-08-24',
    sourceType: 'official',
  },
  {
    id: 'nara-index-stockindex',
    name: 'e-나라지표 · 주가지수',
    publisher: '통계청',
    url: 'https://www.index.go.kr/unity/potal/main/EachDtlPageDetail.do?idx_cd=1080',
    reviewedAt: '2026-08-24',
    sourceType: 'official',
  },
  {
    id: 'krx-kind',
    name: '전자공시시스템(KIND)',
    publisher: '한국거래소',
    url: 'https://kind.krx.co.kr',
    reviewedAt: '2026-08-24',
    sourceType: 'official',
  },
  {
    id: 'bok-fx-reserves',
    name: '외환보유액의 의의',
    publisher: '한국은행',
    url: 'https://www.bok.or.kr/portal/main/contents.do?menuNo=200411',
    reviewedAt: '2026-08-24',
    sourceType: 'official',
  },
  {
    id: 'moef-fiscal-balance',
    name: '시사경제용어사전 · 재정수지',
    publisher: '기획재정부',
    url: 'https://mofe.go.kr/sisa/dictionary/detail?idx=2169',
    reviewedAt: '2026-08-24',
    sourceType: 'official',
  },
  {
    id: 'moef-balance-of-payments',
    name: '시사경제용어사전 · 국제수지',
    publisher: '기획재정부',
    url: 'https://mofe.go.kr/sisa/dictionary/detail?idx=587',
    reviewedAt: '2026-08-24',
    sourceType: 'official',
  },
  {
    id: 'kosis-business-cycle',
    name: '경기순환시계',
    publisher: '통계청',
    url: 'https://kosis.kr/visual/bcc/index/index.do?mb=N',
    reviewedAt: '2026-08-24',
    sourceType: 'official',
  },
  {
    id: 'history-go-kr-oil-shock',
    name: '우리역사넷 · 오일쇼크',
    publisher: '국사편찬위원회',
    url: 'https://contents.history.go.kr/mobile/kc/view.do?levelId=kc_i500270&code=kc_age_50',
    reviewedAt: '2026-08-24',
    sourceType: 'official',
  },
  {
    id: 'fss-insurance-terms',
    name: '자주 쓰이는 보험용어',
    publisher: '금융감독원',
    url: 'https://law.fss.or.kr/main/prc/is/sub/is004.jsp?menuNo=900392',
    reviewedAt: '2026-08-24',
    sourceType: 'official',
  },
  {
    id: 'knia-dictionary',
    name: '보험용어사전',
    publisher: '손해보험협회',
    url: 'https://www.knia.or.kr/howtouse/dictionary',
    reviewedAt: '2026-08-24',
    sourceType: 'official',
  },
  {
    id: 'nts-gain-loss-offset',
    name: '금융투자소득 손익통산 관련 안내',
    publisher: '국세청',
    url: 'https://www.nts.go.kr/nts/cm/cntnts/cntntsView.do?cntntsId=8800&mi=12274',
    reviewedAt: '2026-08-24',
    sourceType: 'official',
  },

  // ── 차근차근 경제사 10개 과정 완성분(2026-08-25 조사) ──────────────
  {
    id: 'voc-history',
    name: 'VOC와 세계 최초의 주식 거래',
    publisher: 'Amsterdam Stock Exchange History Archive',
    url: 'https://www.beursgeschiedenis.nl/en/moment/voc-the-start-of-global-share-trading/',
    reviewedAt: '2026-08-25',
    sourceType: 'academic',
  },
  {
    id: 'eh-net-industrial-revolution',
    name: 'Child Labor during the British Industrial Revolution',
    publisher: 'Economic History Association(EH.net)',
    url: 'https://eh.net/encyclopedia/child-labor-during-the-british-industrial-revolution/',
    reviewedAt: '2026-08-25',
    sourceType: 'academic',
  },
  {
    id: 'fed-history-bretton-woods',
    name: 'Bretton Woods Created',
    publisher: 'Federal Reserve History(미국 연방준비제도 역사 프로젝트)',
    url: 'https://www.federalreservehistory.org/essays/bretton-woods-created',
    reviewedAt: '2026-08-25',
    sourceType: 'official',
  },
  {
    id: 'archives-go-kr-economic-plan',
    name: '경제개발 5개년 계획(제1차)',
    publisher: '국가기록원',
    url: 'https://theme.archives.go.kr/next/economicDevelopment/primary.do',
    reviewedAt: '2026-08-25',
    sourceType: 'official',
  },
  {
    id: 'history-go-kr-imf-crisis',
    name: '우리역사넷 · 1997년 외환위기',
    publisher: '국사편찬위원회',
    url: 'https://contents.history.go.kr/mobile/kc/view.do?levelId=kc_i501300&code=kc_age_50',
    reviewedAt: '2026-08-25',
    sourceType: 'official',
  },
  {
    id: 'kdi-eiec-europe-debt',
    name: '유럽 재정위기 해설',
    publisher: 'KDI 경제정보센터',
    url: 'https://eiec.kdi.re.kr/material/clickView.do?click_yymm=201004&cidx=1185&pp=20&pg=1',
    reviewedAt: '2026-08-25',
    sourceType: 'official',
  },
  {
    id: 'bok-covid-rate-cut',
    name: '기준금리 인하 결정(2020년 3월)',
    publisher: '한국은행',
    url: 'https://www.bok.or.kr/portal/bbs/P0000559/view.do?nttId=10057023&menuNo=200690',
    reviewedAt: '2026-08-25',
    sourceType: 'official',
  },
  {
    id: 'bok-monetary-report-2022',
    name: '통화신용정책보고서(2022년 6월)',
    publisher: '한국은행',
    url: 'https://www.bok.or.kr/portal/bbs/B0000156/view.do?nttId=10070923&menuNo=200067',
    reviewedAt: '2026-08-25',
    sourceType: 'official',
  },
  {
    id: 'fsc-virtual-asset-registration',
    name: '가상자산사업자 신고제도 안내',
    publisher: '금융위원회',
    url: 'https://www.fsc.go.kr/no010101/75560',
    reviewedAt: '2026-08-25',
    sourceType: 'official',
  },
  {
    id: 'easylaw-corporation',
    name: '찾기쉬운 생활법령정보 · 주식회사의 개념',
    publisher: '법제처',
    url: 'https://easylaw.go.kr/CSP/CnpClsMain.laf?popMenu=ov&csmSeq=736&ccfNo=1&cciNo=1&cnpClsNo=2',
    reviewedAt: '2026-08-25',
    sourceType: 'official',
  },
  {
    id: 'easylaw-shareholder-rights',
    name: '찾기쉬운 생활법령정보 · 주주의 권리',
    publisher: '법제처',
    url: 'https://easylaw.go.kr/CSP/CnpClsMainBtr.laf?ccfNo=2&cciNo=2&cnpClsNo=1&csmSeq=1701',
    reviewedAt: '2026-08-25',
    sourceType: 'official',
  },
  {
    id: 'easylaw-stock-trading',
    name: '찾기쉬운 생활법령정보 · 주식거래 방법',
    publisher: '법제처',
    url: 'https://easylaw.go.kr/CSP/CnpClsMain.laf?popMenu=ov&csmSeq=1701&ccfNo=2&cciNo=1&cnpClsNo=2',
    reviewedAt: '2026-08-25',
    sourceType: 'official',
  },
  {
    id: 'easylaw-listing',
    name: '찾기쉬운 생활법령정보 · 상장의 개념 및 요건',
    publisher: '법제처',
    url: 'https://easylaw.go.kr/CSP/CnpClsMain.laf?popMenu=ov&csmSeq=1701&ccfNo=1&cciNo=2&cnpClsNo=1',
    reviewedAt: '2026-08-25',
    sourceType: 'official',
  },
  {
    id: 'easylaw-stock-issuance',
    name: '찾기쉬운 생활법령정보 · 주식의 발행(유상증자·무상증자)',
    publisher: '법제처',
    url: 'https://easylaw.go.kr/CSP/CnpClsMain.laf?csmSeq=1701&ccfNo=1&cciNo=1&cnpClsNo=1',
    reviewedAt: '2026-08-25',
    sourceType: 'official',
  },
  {
    id: 'easylaw-market-alert',
    name: '찾기쉬운 생활법령정보 · 매매거래정지·시장경보제도',
    publisher: '법제처',
    url: 'https://easylaw.go.kr/CSP/CnpClsMain.laf?popMenu=ov&csmSeq=1701&ccfNo=3&cciNo=1&cnpClsNo=1',
    reviewedAt: '2026-08-25',
    sourceType: 'official',
  },
  {
    id: 'dart-intro',
    name: 'DART 소개',
    publisher: '금융감독원',
    url: 'https://dart.fss.or.kr/introduction/content1.do',
    reviewedAt: '2026-08-25',
    sourceType: 'official',
  },
  {
    id: 'fsc-short-selling',
    name: '공매도 제도 개선 및 전면 재개',
    publisher: '금융위원회',
    url: 'https://www.fsc.go.kr/no010101/84216',
    reviewedAt: '2026-08-25',
    effectiveDate: '2025-03-31',
    sourceType: 'official',
  },
  {
    id: 'kcie-etf',
    name: 'ETF 투자 용어(괴리율·추적오차)',
    publisher: '한국경제교육연구원(KCIE)',
    url: 'https://www.kcie.or.kr/mobile/guide/3/18/web_view?content_idx=876',
    reviewedAt: '2026-08-25',
    sourceType: 'institutional',
  },

  // ── 생활로 읽는 경제 12개 과정 신규 출처(2026-08-25 조사) ──────────────
  {
    id: 'opinet-info',
    name: '오피넷(유가정보서비스)',
    publisher: '한국석유공사',
    url: 'https://www.opinet.co.kr',
    reviewedAt: '2026-08-25',
    sourceType: 'official',
  },
  {
    id: 'fao-food-price-index',
    name: 'FAO Food Price Index',
    publisher: 'Food and Agriculture Organization of the United Nations(FAO)',
    url: 'https://www.fao.org/worldfoodsituation/foodpricesindex/en/',
    reviewedAt: '2026-08-25',
    sourceType: 'official',
  },
  {
    id: 'reb-info',
    name: '부동산통계정보시스템(R-ONE)',
    publisher: '한국부동산원',
    url: 'https://www.reb.or.kr',
    reviewedAt: '2026-08-25',
    sourceType: 'official',
  },
  {
    id: 'nts-info',
    name: '국세청 홈페이지',
    publisher: '국세청',
    url: 'https://www.nts.go.kr',
    reviewedAt: '2026-08-25',
    sourceType: 'official',
  },
]
